---

---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted

- name: reload prometheus
  uri:
    url: "http://localhost:{{ prometheus_port | default(9090) }}/-/reload"
    method: POST
    status_code: 200
  ignore_errors: true

