---
# Backup automation handlers
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart backup-monitoring
  systemd:
    name: backup-monitoring
    state: restarted

- name: restart backup-metrics
  systemd:
    name: backup-metrics
    state: restarted
  when: (backup_automation.monitoring.prometheus_metrics | default(false)) | bool

- name: reload cron
  service:
    name: "{{ (ansible_os_family == 'RedHat') | ternary('crond', 'cron') }}"
    state: reloaded

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: reload backup configuration
  command: /var/lib/backup/scripts/reload-backup-config.sh
  become: yes
  become_user: backup
