---
# Backup automation handlers
- name: reload systemd
  systemd:
    daemon_reload: true
  become: true

- name: restart backup-monitoring
  systemd:
    name: backup-monitoring
    state: restarted
  become: true

- name: restart backup-metrics
  systemd:
    name: backup-metrics
    state: restarted
  when: (backup_automation.monitoring.prometheus_metrics | default(false)) | bool
  become: true

- name: restart database-backup-metrics
  systemd:
    name: database-backup-metrics
    state: restarted
  when: (backup_automation.monitoring.prometheus_metrics | default(false)) | bool
  become: true

- name: reload cron
  service:
    name: "{{ (ansible_os_family == 'RedHat') | ternary('crond', 'cron') }}"
    state: restarted
  become: true

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
  become: true

- name: reload backup configuration
  command: /var/lib/backup/scripts/reload-backup-config.sh
  become: true
  become_user: backup
