---
# Backup automation preparation tasks
- name: Update package cache
  package:
    update_cache: yes
  when: ansible_os_family in ['Debian', 'RedHat']

- name: Install required system packages
  package:
    name: "{{ backup_packages }}"
    state: present
  vars:
    backup_packages:
      - cron
      - rsync
      - gzip
      - tar
      - openssl
      - curl
      - jq
      - python3-pip
      - python3-psycopg2
      - postgresql-client
      - redis-tools

- name: Install Python packages for backup automation
  pip:
    name: "{{ python_packages }}"
    state: present
    executable: pip3
  vars:
    python_packages:
      - boto3
      - psycopg2-binary
      - redis
      - cryptography
      - requests
      - pyyaml

- name: Check if AWS CLI is installed
  command: aws --version
  register: aws_cli_check
  failed_when: false
  changed_when: false

- name: Install AWS CLI v2
  block:
    - name: Download AWS CLI installer
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/tmp/awscliv2.zip"
        mode: '0644'

    - name: Extract AWS CLI installer
      unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp"
        remote_src: yes

    - name: Install AWS CLI
      command: /tmp/aws/install
      args:
        creates: /usr/local/bin/aws

    - name: Clean up AWS CLI installer
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/awscliv2.zip"
        - "/tmp/aws"
  when: 
    - remote_storage.enabled
    - remote_storage.type == 's3'
    - aws_cli_check.rc != 0

- name: Gather system information
  setup:
    gather_subset:
      - hardware
      - network
      - virtual

- name: Set backup facts
  set_fact:
    backup_hostname: "{{ ansible_hostname }}"
    backup_timestamp: "{{ ansible_date_time.epoch }}"
    backup_date: "{{ ansible_date_time.date }}"
    backup_time: "{{ ansible_date_time.time }}"

- name: Create backup automation log entry
  lineinfile:
    path: "{{ backup_automation.log_directory }}/backup-automation.log"
    line: "{{ ansible_date_time.iso8601 }} [INFO] Backup automation preparation started on {{ ansible_hostname }}"
    create: yes
    mode: '0640'
    owner: backup
    group: backup
  ignore_errors: yes

- name: Check system resources
  shell: |
    echo "CPU Cores: $(nproc)"
    echo "Memory: $(free -h | grep '^Mem:' | awk '{print $2}')"
    echo "Disk Space: $(df -h {{ backup_automation.base_directory | dirname }} | tail -1 | awk '{print $4}')"
  register: system_resources
  changed_when: false

- name: Log system resources
  debug:
    msg: "System Resources - {{ system_resources.stdout_lines }}"

- name: Verify network connectivity to backup targets
  uri:
    url: "{{ item }}"
    method: HEAD
    timeout: 10
  register: connectivity_check
  failed_when: false
  loop:
    - "https://s3.amazonaws.com"
    - "https://github.com"
  when: remote_storage.enabled

- name: Log connectivity status
  debug:
    msg: "Connectivity to {{ item.item }}: {{ 'OK' if item.status == 200 else 'FAILED' }}"
  loop: "{{ connectivity_check.results }}"
  when: 
    - remote_storage.enabled
    - connectivity_check is defined
