---
# Backup automation security setup
- name: Create backup user group
  group:
    name: backup
    state: present
    system: yes

- name: Create backup user
  user:
    name: backup
    group: backup
    system: yes
    shell: /bin/bash
    home: /var/lib/backup
    create_home: yes
    comment: "HX Backup Automation User"

- name: Set backup user password policy
  user:
    name: backup
    password_lock: yes
  when: backup_security.access_control is defined

- name: Create backup sudoers configuration
  template:
    src: backup-sudoers.j2
    dest: /etc/sudoers.d/backup
    mode: '0440'
    owner: root
    group: root
    validate: 'visudo -cf %s'

- name: Configure backup user SSH access
  authorized_key:
    user: backup
    key: "{{ item }}"
    state: present
  loop: "{{ backup_ssh_keys | default([]) }}"
  when: backup_ssh_keys is defined

- name: Create backup security directories
  file:
    path: "{{ item }}"
    state: directory
    owner: backup
    group: backup
    mode: "{{ backup_security.directory_permissions }}"
  loop:
    - /etc/hx-backup
    - /var/lib/backup/.ssh
    - /var/lib/backup/scripts

- name: Generate backup encryption key
  command: openssl rand -base64 32
  register: backup_encryption_key
  when: 
    - backup_automation.encryption.enabled
    - not ansible_check_mode

- name: Store backup encryption key
  copy:
    content: "{{ backup_encryption_key.stdout }}"
    dest: "{{ backup_automation.encryption.key_file }}"
    owner: backup
    group: backup
    mode: "{{ backup_security.file_permissions }}"
  when: 
    - backup_automation.encryption.enabled
    - backup_encryption_key is defined
    - not ansible_check_mode

- name: Create backup key rotation script
  template:
    src: rotate-backup-key.sh.j2
    dest: /var/lib/backup/scripts/rotate-backup-key.sh
    owner: backup
    group: backup
    mode: '0750'

- name: Configure SELinux contexts for backup directories
  sefcontext:
    target: "{{ item }}"
    setype: admin_home_t
    state: present
  loop:
    - "{{ backup_automation.base_directory }}(/.*)?"
    - "/var/lib/backup(/.*)?"
    - "/etc/hx-backup(/.*)?"
  when: 
    - ansible_selinux.status == "enabled"
    - backup_security.selinux_context is defined

- name: Apply SELinux contexts
  command: restorecon -R {{ item }}
  loop:
    - "{{ backup_automation.base_directory }}"
    - "/var/lib/backup"
    - "/etc/hx-backup"
  when: 
    - ansible_selinux.status == "enabled"
    - backup_security.selinux_context is defined

- name: Configure backup file permissions
  file:
    path: "{{ item }}"
    owner: "{{ backup_security.owner }}"
    group: "{{ backup_security.group }}"
    mode: "{{ backup_security.directory_permissions }}"
    state: directory
  loop:
    - "{{ backup_automation.base_directory }}"
    - "{{ backup_automation.temp_directory }}"
    - "{{ backup_automation.log_directory }}"

- name: Create backup access control script
  template:
    src: backup-access-control.sh.j2
    dest: /var/lib/backup/scripts/backup-access-control.sh
    owner: backup
    group: backup
    mode: '0750'

- name: Configure backup log rotation
  template:
    src: backup-logrotate.j2
    dest: /etc/logrotate.d/hx-backup
    owner: root
    group: root
    mode: '0644'

- name: Create backup security audit script
  template:
    src: backup-security-audit.sh.j2
    dest: /var/lib/backup/scripts/backup-security-audit.sh
    owner: backup
    group: backup
    mode: '0750'

- name: Schedule backup security audit
  cron:
    name: "Backup Security Audit"
    user: backup
    job: "/var/lib/backup/scripts/backup-security-audit.sh"
    minute: "0"
    hour: "6"
    day: "1"
    state: present

- name: Create backup integrity verification key
  command: openssl rand -hex 32
  register: backup_integrity_key
  when: 
    - verification.enabled
    - not ansible_check_mode

- name: Store backup integrity key
  copy:
    content: "{{ backup_integrity_key.stdout }}"
    dest: /etc/hx-backup/integrity.key
    owner: backup
    group: backup
    mode: "{{ backup_security.file_permissions }}"
  when: 
    - verification.enabled
    - backup_integrity_key is defined
    - not ansible_check_mode

- name: Configure backup user limits
  pam_limits:
    domain: backup
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
  loop:
    - { type: 'soft', item: 'nofile', value: '65536' }
    - { type: 'hard', item: 'nofile', value: '65536' }
    - { type: 'soft', item: 'nproc', value: '32768' }
    - { type: 'hard', item: 'nproc', value: '32768' }
