---

---
# Configuration Validator Role Metadata - Phase 3 Day 1

galaxy_info:
  role_name: config_validator
  namespace: hx_infrastructure
  author: HX Infrastructure Team
  description: Comprehensive configuration validation and standardization framework
  company: Hana-X Platform
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - "20.04"
        - "22.04"
        - "24.04"
    - name: Debian
      versions:
        - "10"
        - "11"
        - "12"
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - infrastructure
    - configuration
    - validation
    - standardization
    - reliability
    - consistency

dependencies: []

