
---
# Ansible Collections Requirements for HX Infrastructure
collections:
  # Core Ansible Collections
  - name: ansible.posix
    version: ">=1.5.4"
    source: https://galaxy.ansible.com

  - name: community.general
    version: ">=8.0.0"
    source: https://galaxy.ansible.com

  - name: community.crypto
    version: ">=2.15.0"
    source: https://galaxy.ansible.com

  - name: community.docker
    version: ">=3.4.0"
    source: https://galaxy.ansible.com

  - name: community.postgresql
    version: ">=3.2.0"
    source: https://galaxy.ansible.com

  - name: community.mysql
    version: ">=3.7.0"
    source: https://galaxy.ansible.com

  # Security and Certificate Management
  - name: community.crypto
    version: ">=2.15.0"
    source: https://galaxy.ansible.com

  - name: ansible.windows
    version: ">=2.0.0"
    source: https://galaxy.ansible.com

  # Cloud Providers
  - name: amazon.aws
    version: ">=7.0.0"
    source: https://galaxy.ansible.com

  - name: azure.azcollection
    version: ">=1.19.0"
    source: https://galaxy.ansible.com

  - name: google.cloud
    version: ">=1.2.0"
    source: https://galaxy.ansible.com

  # Kubernetes and Container Management
  - name: kubernetes.core
    version: ">=2.4.0"
    source: https://galaxy.ansible.com

  - name: community.kubernetes
    version: ">=2.0.0"
    source: https://galaxy.ansible.com

  # Monitoring and Observability
  - name: community.grafana
    version: ">=1.5.0"
    source: https://galaxy.ansible.com

  - name: prometheus.prometheus
    version: ">=0.13.0"
    source: https://galaxy.ansible.com

  # Network Management
  - name: cisco.ios
    version: ">=5.0.0"
    source: https://galaxy.ansible.com

  - name: junipernetworks.junos
    version: ">=5.3.0"
    source: https://galaxy.ansible.com

  # Virtualization
  - name: community.vmware
    version: ">=4.0.0"
    source: https://galaxy.ansible.com

  - name: community.libvirt
    version: ">=1.3.0"
    source: https://galaxy.ansible.com

# Ansible Roles from Galaxy
roles:
  # Common infrastructure roles
  - name: geerlingguy.docker
    version: "7.0.2"
    src: https://galaxy.ansible.com

  - name: geerlingguy.postgresql
    version: "3.4.2"
    src: https://galaxy.ansible.com

  - name: geerlingguy.nginx
    version: "3.1.4"
    src: https://galaxy.ansible.com

  - name: geerlingguy.redis
    version: "1.8.0"
    src: https://galaxy.ansible.com

  - name: geerlingguy.security
    version: "2.0.1"
    src: https://galaxy.ansible.com

  # Certificate and PKI management
  - name: community.crypto.acme_certificate
    version: "2.15.0"
    src: https://galaxy.ansible.com

  # Monitoring roles
  - name: cloudalchemy.prometheus
    version: "2.17.0"
    src: https://galaxy.ansible.com

  - name: cloudalchemy.grafana
    version: "0.22.3"
    src: https://galaxy.ansible.com

  - name: cloudalchemy.node_exporter
    version: "3.0.0"
    src: https://galaxy.ansible.com
