---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == "Debian"
  
  roles:
    - role: hx_webui_install_standardized
      vars:
        # Override sensitive defaults for testing
        vault_postgres_password: "test_password_123"
        vault_litellm_master_key: "test_master_key_12345678901234567890"
        vault_litellm_db_password: "test_db_password_123"
        vault_openai_api_key: "sk-test1234567890abcdef"
        vault_anthropic_api_key: "sk-ant-test1234567890abcdef"
        # Disable external dependencies for testing
        hx_litellm_providers:
          openai:
            enabled: false
          anthropic:
            enabled: false
        hx_litellm_database_enabled: false
        hx_litellm_caching_enabled: false
