---
# HX Infrastructure Production Inventory
# This replaces the template inventory with real production configuration

all:
  children:
    control_nodes:
      hosts:
        hx-control01:
          ansible_host: 192.168.10.5
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/hx-infrastructure-key

    llm_servers:
      hosts:
        hx-llm01-server:
          ansible_host: 192.168.10.6
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/hx-infrastructure-key
          gpu_count: 4
          gpu_type: "A100"
        hx-llm02-server:
          ansible_host: 192.168.10.7
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/hx-infrastructure-key
          gpu_count: 4
          gpu_type: "A100"

    web_servers:
      hosts:
        hx-web01:
          ansible_host: 192.168.10.10
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/hx-infrastructure-key
        hx-web02:
          ansible_host: 192.168.10.11
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/hx-infrastructure-key

    app_servers:
      hosts:
        hx-app01:
          ansible_host: 192.168.10.15
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/hx-infrastructure-key
        hx-app02:
          ansible_host: 192.168.10.16
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/hx-infrastructure-key

    database_servers:
      hosts:
        hx-db01:
          ansible_host: 192.168.10.20
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/hx-infrastructure-key
          db_role: primary
        hx-db02:
          ansible_host: 192.168.10.21
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/hx-infrastructure-key
          db_role: replica

    load_balancers:
      hosts:
        hx-lb01:
          ansible_host: 192.168.10.25
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/hx-infrastructure-key
        hx-lb02:
          ansible_host: 192.168.10.26
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/hx-infrastructure-key

    monitoring_servers:
      hosts:
        hx-monitor01:
          ansible_host: 192.168.10.30
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/hx-infrastructure-key

  vars:
    # Global variables for all hosts
    hx_environment: production
    hx_domain: hanax.ai
    hx_timezone: UTC
    hx_ntp_servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
    hx_dns_servers:
      - 8.8.8.8
      - 8.8.4.4
