
---
# HX Infrastructure - Production Environment Inventory
# 15-Server Architecture Configuration

all:
  vars:
    # Global Environment Variables
    environment: production
    domain_name: hx-infrastructure.com
    timezone: UTC
    
    # Network Configuration
    network_cidr: 10.0.0.0/16
    management_network: 10.0.10.0/24
    
    # Security Configuration
    ssh_port: 22
    firewall_enabled: true
    fail2ban_enabled: true
    
    # SSL Configuration
    ssl_enabled: true
    ssl_certificate_path: /etc/ssl/certs
    ssl_private_key_path: /etc/ssl/private
    
    # Monitoring Configuration
    monitoring_enabled: true
    log_aggregation_enabled: true
    metrics_retention_days: 90
    
    # Backup Configuration
    backup_enabled: true
    backup_retention_days: 30
    backup_schedule: "0 2 * * *"

  children:
    # Load Balancer Tier - 2 Servers
    load_balancers:
      vars:
        nginx_worker_processes: 2
        nginx_worker_connections: 2048
        keepalived_enabled: true
        virtual_ip: 10.0.1.100
      hosts:
        lb-01:
          ansible_host: 10.0.1.10
          ansible_user: ubuntu
          keepalived_priority: 110
          keepalived_state: MASTER
        lb-02:
          ansible_host: 10.0.1.11
          ansible_user: ubuntu
          keepalived_priority: 100
          keepalived_state: BACKUP

    # Web Tier - 3 Servers
    web_servers:
      vars:
        nginx_worker_processes: auto
        nginx_worker_connections: 1024
        nginx_keepalive_timeout: 65
        nginx_client_max_body_size: 64m
        nginx_gzip_enabled: true
      hosts:
        web-01:
          ansible_host: 10.0.2.10
          ansible_user: ubuntu
        web-02:
          ansible_host: 10.0.2.11
          ansible_user: ubuntu
        web-03:
          ansible_host: 10.0.2.12
          ansible_user: ubuntu

    # Application Tier - 3 Servers
    app_servers:
      vars:
        app_port: 8080
        app_environment: production
        app_max_memory: 4g
        app_min_memory: 2g
        jvm_opts: "-XX:+UseG1GC -XX:MaxGCPauseMillis=200"
      hosts:
        app-01:
          ansible_host: 10.0.3.10
          ansible_user: ubuntu
        app-02:
          ansible_host: 10.0.3.11
          ansible_user: ubuntu
        app-03:
          ansible_host: 10.0.3.12
          ansible_user: ubuntu

    # Database Tier - 3 Servers (1 Master, 2 Replicas)
    database_servers:
      vars:
        postgresql_version: "15"
        postgresql_port: 5432
        postgresql_max_connections: 200
        postgresql_shared_buffers: 4GB
        postgresql_effective_cache_size: 12GB
        postgresql_work_mem: 64MB
        postgresql_maintenance_work_mem: 512MB
      hosts:
        db-01:
          ansible_host: 10.0.4.10
          ansible_user: ubuntu
          postgresql_role: master
          postgresql_server_id: 1
        db-02:
          ansible_host: 10.0.4.11
          ansible_user: ubuntu
          postgresql_role: replica
          postgresql_server_id: 2
          postgresql_master_host: 10.0.4.10
        db-03:
          ansible_host: 10.0.4.12
          ansible_user: ubuntu
          postgresql_role: replica
          postgresql_server_id: 3
          postgresql_master_host: 10.0.4.10

    # Cache Tier - 2 Servers (1 Master, 1 Replica)
    cache_servers:
      vars:
        redis_port: 6379
        redis_maxmemory: 6gb
        redis_maxmemory_policy: allkeys-lru
        redis_save_enabled: true
        redis_appendonly: true
      hosts:
        cache-01:
          ansible_host: 10.0.5.10
          ansible_user: ubuntu
          redis_role: master
        cache-02:
          ansible_host: 10.0.5.11
          ansible_user: ubuntu
          redis_role: replica
          redis_master_host: 10.0.5.10

    # Monitoring Tier - 2 Servers
    monitoring_servers:
      vars:
        prometheus_retention_time: 90d
        prometheus_storage_retention_size: 100GB
        grafana_admin_user: admin
        grafana_port: 3000
        elasticsearch_heap_size: 4g
        kibana_port: 5601
      hosts:
        monitor-01:
          ansible_host: 10.0.6.10
          ansible_user: ubuntu
          monitoring_role: metrics
          services:
            - prometheus
            - grafana
            - node-exporter
            - alertmanager
        log-01:
          ansible_host: 10.0.6.11
          ansible_user: ubuntu
          monitoring_role: logging
          services:
            - elasticsearch
            - kibana
            - logstash
            - filebeat

    # Logical Groupings for Management
    frontend:
      children:
        - load_balancers
        - web_servers

    backend:
      children:
        - app_servers
        - database_servers
        - cache_servers

    infrastructure:
      children:
        - monitoring_servers

    # Environment-specific groupings
    production_servers:
      children:
        - load_balancers
        - web_servers
        - app_servers
        - database_servers
        - cache_servers
        - monitoring_servers
