
---
# SSH role - default variables
# Secure SSH configuration with hardened defaults

# SSH server configuration
ssh_port: 22
ssh_protocol: 2
ssh_listen_addresses:
  - "0.0.0.0"

# Authentication settings
ssh_permit_root_login: false
ssh_pubkey_authentication: true
ssh_password_authentication: false
ssh_challenge_response_authentication: false
ssh_pam_authentication: true
ssh_empty_passwords: false

# Security hardening
ssh_x11_forwarding: false
ssh_x11_display_offset: 10
ssh_print_motd: false
ssh_tcp_keep_alive: true
ssh_client_alive_interval: 600
ssh_client_alive_count_max: 3
ssh_compression: false
ssh_use_dns: false
ssh_permit_tunnel: false
ssh_allow_agent_forwarding: false
ssh_allow_tcp_forwarding: false
ssh_gateway_ports: false
ssh_permit_user_environment: false

# Logging
ssh_log_level: "INFO"
ssh_syslog_facility: "AUTH"

# Key exchange and encryption
ssh_kex_algorithms:
  - curve25519-sha256@libssh.org
  - ecdh-sha2-nistp521
  - ecdh-sha2-nistp384
  - ecdh-sha2-nistp256
  - diffie-hellman-group16-sha512

ssh_ciphers:
  - chacha20-poly1305@openssh.com
  - aes256-gcm@openssh.com
  - aes128-gcm@openssh.com
  - aes256-ctr
  - aes192-ctr
  - aes128-ctr

ssh_macs:
  - hmac-sha2-256-etm@openssh.com
  - hmac-sha2-512-etm@openssh.com
  - hmac-sha2-256
  - hmac-sha2-512

# Connection limits
ssh_max_auth_tries: 3
ssh_max_sessions: 10
ssh_max_startups: "10:30:60"

# User/group restrictions (empty by default - configure per environment)
ssh_allow_users: []
ssh_allow_groups: []
ssh_deny_users: []
ssh_deny_groups: []

# Client configuration
ssh_client_host_key_algorithms:
  - ssh-ed25519-cert-v01@openssh.com
  - ssh-rsa-cert-v01@openssh.com
  - ssh-ed25519
  - ecdsa-sha2-nistp521
  - ecdsa-sha2-nistp384
  - ecdsa-sha2-nistp256
  - rsa-sha2-512
  - rsa-sha2-256

# Service management
ssh_service_enabled: true
ssh_service_state: started
