---
# PostgreSQL Installation Tasks
- name: "Hx | PostgreSQL Auth | Install PostgreSQL packages"
  package:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
      - postgresql-client
    state: present
  become: true
  tags: ['installation']

- name: "Hx | PostgreSQL Auth | Ensure PostgreSQL service is enabled and started"
  systemd:
    name: postgresql
    enabled: true
    state: started
  become: true
  tags: ['installation']

- name: "Hx | PostgreSQL Auth | Initialize PostgreSQL database"
  command: postgresql-setup initdb
  become: true
  become_user: postgres
  args:
    creates: /var/lib/pgsql/data/postgresql.conf
  when: ansible_os_family == "RedHat"
  tags: ['installation']
