---
- name: "Hx | PostgreSQL Auth | Ensure PostgreSQL extensions are installed"
  package:
    name:
      - postgresql-contrib
      - postgresql-client
    state: present
  tags: ['install']

- name: "Hx | PostgreSQL Auth | Install Python driver for PostgreSQL modules"
  package:
    name: "{{ hx_pg_python_driver_pkg | default('python3-psycopg2') }}"
    state: present
  tags: ['install']

- name: "Hx | PostgreSQL Auth | Install additional security packages"
  package:
    name:
      - fail2ban
      - logrotate
    state: present
  tags: ['install']

- name: "Hx | PostgreSQL Auth | Configure fail2ban for PostgreSQL"
  template:
    src: postgresql-fail2ban.conf.j2
    dest: /etc/fail2ban/jail.d/postgresql.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban
  tags: ['install']

- name: "Hx | PostgreSQL Auth | Configure logrotate for PostgreSQL"
  template:
    src: postgresql-logrotate.j2
    dest: /etc/logrotate.d/postgresql
    owner: root
    group: root
    mode: '0644'
  tags: ['install']

- name: "Hx | PostgreSQL Auth | Create monitoring user"
  postgresql_user:
  no_log: true
    name: "monitoring"
    password: "{{ vault_monitoring_password }}"
    role_attr_flags: "NOSUPERUSER,NOCREATEDB,NOCREATEROLE"
  become: true
  become_user: postgres
  when:
    - vault_monitoring_password is defined
    - vault_monitoring_password not in ['monitoring_change_me', 'CHANGE_ME', '', None]
  tags: ['install']

- name: "Hx | PostgreSQL Auth | Grant monitoring permissions"
  postgresql_privs:
    database: "postgres"
    roles: "monitoring"
    privs: "CONNECT"
    type: "database"
  become: true
  become_user: postgres
  when:
    - vault_monitoring_password is defined
    - vault_monitoring_password not in ['monitoring_change_me', 'CHANGE_ME', '', None]
  tags: ['install']
