---
# Application Deployment Playbook
- name: Application Deployment
  hosts: webservers
  become: true
  gather_facts: true

  roles:
    - geerlingguy.nginx

  tasks:
    - name: Ensure application directory exists
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Deploy application files
      ansible.builtin.template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
