---
# Application Deployment Playbook
- name: Application Deployment
  hosts: webservers
  become: yes
  gather_facts: yes
  
  roles:
    - geerlingguy.nginx
  
  tasks:
    - name: Ensure application directory exists
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
        
    - name: Deploy application files
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
