---

# Infrastructure Services Group Variables
# Domain Controllers and Certificate Authorities

# Windows Server Configuration
windows:
  domain_name: "{{ domain_name }}"
  netbios_name: "{{ domain_name.split('.')[0] | upper }}"
  forest_mode: "WinThreshold"
  domain_mode: "WinThreshold"
  safe_mode_password: "{{ vault_safe_mode_password }}"

# Active Directory Configuration
active_directory:
  install_dns: true
  install_dhcp: true
  create_dns_delegation: false
  database_path: "C:\\Windows\\NTDS"
  sysvol_path: "C:\\Windows\\SYSVOL"
  log_path: "C:\\Windows\\NTDS"

  # Organizational Units
  organizational_units:
    - name: "HX-Infrastructure"
      path: "OU=HX-Infrastructure,DC={{ domain_name.split('.') | join(',DC=') }}"
    - name: "Servers"
      path: "OU=Servers,OU=HX-Infrastructure,DC={{ domain_name.split('.') | join(',DC=') }}"
    - name: "Workstations"
      path: "OU=Workstations,OU=HX-Infrastructure,DC={{ domain_name.split('.') | join(',DC=') }}"
    - name: "Users"
      path: "OU=Users,OU=HX-Infrastructure,DC={{ domain_name.split('.') | join(',DC=') }}"
    - name: "Service Accounts"
      path: "OU=Service Accounts,OU=HX-Infrastructure,DC={{ domain_name.split('.') | join(',DC=') }}"

  # Group Policy
  group_policies:
    - name: "HX-Security-Policy"
      description: "Security hardening for HX Infrastructure"
    - name: "HX-Server-Policy"
      description: "Server-specific configurations"

# DNS Configuration
dns:
  forwarders:
    - 8.8.8.8
    - 8.8.4.4
    - 1.1.1.1

  zones:
    - name: "{{ domain_name }}"
      type: primary
    - name: "{{ network_subnet.split('/')[0].split('.')[0:3] | join('.') }}.in-addr.arpa"
      type: primary

# DHCP Configuration
dhcp:
  scope_name: "HX-Infrastructure-Scope"
  scope_description: "DHCP scope for HX Infrastructure"
  start_range: "{{ network_subnet.split('/')[0].split('.')[0:3] | join('.') }}.100"
  end_range: "{{ network_subnet.split('/')[0].split('.')[0:3] | join('.') }}.200"
  subnet_mask: "255.255.255.0"
  default_gateway: "{{ network_subnet.split('/')[0].split('.')[0:3] | join('.') }}.1"
  dns_servers:
    - "{{ network_subnet.split('/')[0].split('.')[0:3] | join('.') }}.10"
    - "{{ network_subnet.split('/')[0].split('.')[0:3] | join('.') }}.11"
  lease_duration: "8.00:00:00"  # 8 days

# Certificate Authority Configuration
certificate_authority:
  ca_name: "HX-Infrastructure-CA"
  ca_description: "HX Infrastructure Certificate Authority"
  key_length: 4096
  hash_algorithm: SHA256
  validity_period: "10 years"

  # Certificate Templates
  certificate_templates:
    - name: "HX-Server-Certificate"
      description: "Server certificates for HX Infrastructure"
      key_usage: ["Digital Signature", "Key Encipherment"]
      enhanced_key_usage: ["Server Authentication"]
      validity_period: "2 years"

    - name: "HX-Client-Certificate"
      description: "Client certificates for HX Infrastructure"
      key_usage: ["Digital Signature"]
      enhanced_key_usage: ["Client Authentication"]
      validity_period: "1 year"

    - name: "HX-Code-Signing"
      description: "Code signing certificates"
      key_usage: ["Digital Signature"]
      enhanced_key_usage: ["Code Signing"]
      validity_period: "3 years"

  # Certificate Revocation List
  crl:
    publication_interval: "1 week"
    next_update_interval: "1 day"
    delta_crl_interval: "1 day"

# Windows Features to Install
windows_features:
  - AD-Domain-Services
  - DNS
  - DHCP
  - ADCS-Cert-Authority
  - ADCS-Web-Enrollment
  - RSAT-AD-Tools
  - RSAT-DNS-Server
  - RSAT-DHCP

# Windows Services Configuration
windows_services:
  - name: "DNS"
    state: started
    start_mode: auto
  - name: "DHCP Server"
    state: started
    start_mode: auto
  - name: "Active Directory Domain Services"
    state: started
    start_mode: auto
  - name: "Certificate Services"
    state: started
    start_mode: auto

# Security Configuration
security:
  password_policy:
    minimum_password_length: 12
    password_complexity: true
    maximum_password_age: 90
    minimum_password_age: 1
    password_history_count: 24
    lockout_threshold: 5
    lockout_duration: 30
    lockout_observation_window: 30

  audit_policy:
    audit_account_logon: "Success,Failure"
    audit_account_management: "Success,Failure"
    audit_directory_service_access: "Success,Failure"
    audit_logon_events: "Success,Failure"
    audit_object_access: "Failure"
    audit_policy_change: "Success,Failure"
    audit_privilege_use: "Failure"
    audit_process_tracking: "No Auditing"
    audit_system_events: "Success,Failure"

# Backup Configuration
backup:
  system_state: true
  active_directory: true
  certificate_authority: true
  schedule: "Daily at 2:00 AM"
  retention: "30 days"
  location: "\\\\backup-server\\infrastructure-backups"

# Monitoring Configuration
monitoring:
  performance_counters:
    - "\\Processor(_Total)\\% Processor Time"
    - "\\Memory\\Available MBytes"
    - "\\LogicalDisk(_Total)\\% Free Space"
    - "\\Network Interface(*)\\Bytes Total/sec"
    - "\\DirectoryServices(NTDS)\\LDAP Searches/sec"
    - "\\DirectoryServices(NTDS)\\LDAP Binds/sec"

  event_logs:
    - Application
    - System
    - Security
    - "Directory Service"
    - "DNS Server"
    - "DHCP Server"

# Network Configuration
network:
  interfaces:
    - name: "Ethernet"
      ip_address: "{{ ansible_host }}"
      subnet_mask: "255.255.255.0"
      default_gateway: "{{ network_subnet.split('/')[0].split('.')[0:3] | join('.') }}.1"
      dns_servers:
        - "127.0.0.1"
        - "{{ dns_servers[0] }}"

# Time Configuration
time:
  ntp_servers:
    - time.windows.com
    - time.nist.gov
    - pool.ntp.org
  timezone: "UTC"

# Logging Configuration
logging:
  log_level: "Information"
  max_log_size: "100MB"
  log_retention_days: 90

  # Event Log Sizes
  event_log_sizes:
    Application: "100MB"
    System: "100MB"
    Security: "200MB"
    "Directory Service": "100MB"
    "DNS Server": "50MB"
    "DHCP Server": "50MB"

# PowerShell Configuration
powershell:
  execution_policy: "RemoteSigned"
  script_block_logging: true
  module_logging: true
  transcription_logging: true
  transcription_output_directory: "C:\\PowerShell_Transcripts"

# Windows Update Configuration
windows_update:
  automatic_updates: true
  install_updates_automatically: false
  download_updates_automatically: true
  notify_before_installation: true
  scheduled_install_day: "Sunday"
  scheduled_install_time: "03:00"
