
---
# Main tasks for hx_ca_trust_standardized role
# Implements SOLID principles with comprehensive certificate authority management

- name: Include validation tasks
  ansible.builtin.include_tasks: validate.yml
  tags: [validation, always]

- name: Include preparation tasks
  ansible.builtin.include_tasks: prepare.yml
  tags: [preparation, setup]

- name: Include installation tasks
  ansible.builtin.include_tasks: install.yml
  tags: [installation, certificates]

- name: Include configuration tasks
  ansible.builtin.include_tasks: configure.yml
  tags: [configuration, setup]

- name: Include security tasks
  ansible.builtin.include_tasks: security.yml
  tags: [security, hardening]

- name: Include verification tasks
  ansible.builtin.include_tasks: verify.yml
  tags: [verification, testing]
  when: hx_ca_trust_run_tests | default(true)
