---
# Production Health Monitoring
- name: Comprehensive Health Monitoring
  hosts: "{{ target_hosts | default('all') }}"
  become: true
  gather_facts: true
  vars:
    monitoring_interval: "{{ health_check_interval | default(60) }}"
    alert_thresholds:
      cpu_usage: 80
      memory_usage: 85
      disk_usage: 90

  tasks:
    - name: System Health Checks
      ansible.builtin.include_role:
        name: health_monitoring
        tasks_from: system_health_check

    - name: Application Performance Monitoring
      ansible.builtin.include_role:
        name: health_monitoring
        tasks_from: apm_monitoring

    - name: Infrastructure Monitoring
      ansible.builtin.include_role:
        name: health_monitoring
        tasks_from: infrastructure_monitoring

    - name: SLA Monitoring and Reporting
      ansible.builtin.include_role:
        name: health_monitoring
        tasks_from: sla_monitoring

    - name: Predictive Failure Detection
      ansible.builtin.include_role:
        name: health_monitoring
        tasks_from: predictive_monitoring
