---
# Service Management Automation
- name: Production Service Management
  hosts: "{{ target_hosts | default('all') }}"
  become: true
  gather_facts: true
  vars:
    service_discovery_enabled: true
    auto_recovery_enabled: true

  tasks:
    - name: Service Discovery and Registration
      ansible.builtin.include_role:
        name: production_ops
        tasks_from: service_discovery

    - name: Service Health Monitoring
      ansible.builtin.include_role:
        name: health_monitoring
        tasks_from: service_health_check

    - name: Service Dependency Management
      ansible.builtin.include_role:
        name: production_ops
        tasks_from: dependency_management

    - name: Auto-Recovery Implementation
      ansible.builtin.include_role:
        name: production_ops
        tasks_from: auto_recovery
      when: auto_recovery_enabled | default(true)

    - name: Graceful Service Management
      ansible.builtin.include_role:
        name: production_ops
        tasks_from: graceful_service_management
