
---
# Production environment inventory - UPDATED PER CRITICAL DIRECTIVE
# Corrected IP addresses to match actual infrastructure (192.168.10.x range)

all:
  children:
    production_servers:
      children:
        web_servers:
          hosts:
            hx-webui-server.dev-test.hana-x.ai:
              ansible_host: 192.168.10.11
              server_role: web_ui
              environment_type: production
        
        app_servers:
          hosts:
            hx-api-server.dev-test.hana-x.ai:
              ansible_host: 192.168.10.5
              server_role: api_gateway
              environment_type: production
            hx-orchestrator-server.dev-test.hana-x.ai:
              ansible_host: 192.168.10.8
              server_role: orchestration
              environment_type: production
        
        database_servers:
          hosts:
            hx-postgres-server.dev-test.hana-x.ai:
              ansible_host: 192.168.10.10
              server_role: database
              environment_type: production
            hx-vectordb-server.dev-test.hana-x.ai:
              ansible_host: 192.168.10.9
              server_role: vector_database
              environment_type: production
        
        llm_servers:
          hosts:
            hx-llm01-server.dev-test.hana-x.ai:
              ansible_host: 192.168.10.6
              server_role: llm_inference
              environment_type: production
              gpu_config: "2x RTX 4070 16GB"
            hx-llm02-server.dev-test.hana-x.ai:
              ansible_host: 192.168.10.7
              server_role: llm_inference
              environment_type: production
              gpu_config: "2x RTX 5060 16GB"
        
        infrastructure_servers:
          hosts:
            hx-dc-server.dev-test.hana-x.ai:
              ansible_host: 192.168.10.2
              server_role: domain_controller
              environment_type: production
            hx-ca-server.dev-test.hana-x.ai:
              ansible_host: 192.168.10.4
              server_role: certificate_authority
              environment_type: production
            hx-devops-server.dev-test.hana-x.ai:
              ansible_host: 192.168.10.14
              server_role: control_node
              environment_type: production

      vars:
        ansible_user: agent0
        ansible_become: true
        ansible_become_method: sudo
        domain_name: dev-test.hana-x.ai
        network_subnet: 192.168.10.0/24
        network_gateway: 192.168.10.1
        dns_servers:
          - 192.168.10.2
        ntp_servers:
          - 0.pool.ntp.org
          - 1.pool.ntp.org
        maintenance_window: "Sunday 02:00-04:00 UTC"
        # Security configurations - HARDENED PER DIRECTIVE
        ansible_ssh_common_args: '-o StrictHostKeyChecking=yes -o IdentitiesOnly=yes'
        ansible_ssh_pipelining: false
        ansible_ssh_retries: 2
        ansible_connection_timeout: 30
        ansible_command_timeout: 300
        backup_enabled: true
        monitoring_enabled: true
        backup_retention_days: 30

  vars:
    # Global variables for production environment
    domain_name: dev-test.hana-x.ai
