---

---
# Production environment inventory (placeholder)
# Following Ansible inventory best practices

all:
  children:
    production_servers:
      hosts:
        # Production hosts will be defined when ready for production deployment
        # This is a placeholder for future production configuration
      vars:
        ansible_user: agent0
        ansible_become: true
        ansible_become_method: sudo
        environment_type: production
        backup_enabled: true
        monitoring_enabled: true
        backup_retention_days: 30
        # Security configurations
        ansible_ssh_common_args: '-o StrictHostKeyChecking=yes -o UserKnownHostsFile=~/.ssh/known_hosts_prod'
        ansible_ssh_pipelining: false  # Disabled for security in production
        ansible_ssh_retries: 2
        # Connection security
        ansible_connection_timeout: 30
        ansible_command_timeout: 300

  vars:
    # Global variables for production environment
    domain_name: hana-x.ai
    # Production-specific configurations will be added later
