
# HX Infrastructure Production Environment Inventory
# Domain: hana-x.ai
# Network: 10.0.0.0/16 (Production Network)
# Authentication: agent0 user (agent0@hana-x.ai)

all:
  children:
    # Infrastructure Services Group (High Availability)
    infrastructure:
      children:
        domain_controllers:
          hosts:
            hx-dc-prod-01.hana-x.ai:
              ansible_host: 10.0.1.10
              server_role: primary_domain_controller
              services: ['active_directory', 'dns', 'dhcp', 'group_policy']
              os_type: windows_server
              memory_gb: 16
              cpu_cores: 8
              availability_zone: az-1
            
            hx-dc-prod-02.hana-x.ai:
              ansible_host: 10.0.1.11
              server_role: secondary_domain_controller
              services: ['active_directory', 'dns', 'dhcp', 'failover']
              os_type: windows_server
              memory_gb: 16
              cpu_cores: 8
              availability_zone: az-2
        
        certificate_authorities:
          hosts:
            hx-ca-prod-01.hana-x.ai:
              ansible_host: 10.0.1.20
              server_role: primary_certificate_authority
              services: ['pki', 'ssl_certificates', 'code_signing', 'ocsp']
              os_type: windows_server
              memory_gb: 8
              cpu_cores: 4
              availability_zone: az-1
            
            hx-ca-prod-02.hana-x.ai:
              ansible_host: 10.0.1.21
              server_role: secondary_certificate_authority
              services: ['pki', 'ssl_certificates', 'failover']
              os_type: windows_server
              memory_gb: 8
              cpu_cores: 4
              availability_zone: az-2
    
    # AI/ML Services Group (Scalable Production)
    ai_ml:
      children:
        llm_gateways:
          hosts:
            hx-litellm-prod-01.hana-x.ai:
              ansible_host: 10.0.2.10
              server_role: litellm_primary
              services: ['litellm', 'api_gateway', 'model_routing', 'rate_limiting']
              os_type: linux
              memory_gb: 32
              cpu_cores: 16
              gpu_enabled: true
              gpu_memory_gb: 48
              availability_zone: az-1
            
            hx-litellm-prod-02.hana-x.ai:
              ansible_host: 10.0.2.11
              server_role: litellm_secondary
              services: ['litellm', 'api_gateway', 'load_balancing', 'failover']
              os_type: linux
              memory_gb: 32
              cpu_cores: 16
              gpu_enabled: true
              gpu_memory_gb: 48
              availability_zone: az-2
        
        llm_inference:
          hosts:
            hx-ollama-prod-01.hana-x.ai:
              ansible_host: 10.0.2.20
              server_role: ollama_primary
              services: ['ollama', 'llama_models', 'high_performance_inference']
              os_type: linux
              memory_gb: 64
              cpu_cores: 32
              gpu_enabled: true
              gpu_memory_gb: 80
              availability_zone: az-1
            
            hx-ollama-prod-02.hana-x.ai:
              ansible_host: 10.0.2.21
              server_role: ollama_secondary
              services: ['ollama', 'llama_models', 'load_balancing']
              os_type: linux
              memory_gb: 64
              cpu_cores: 32
              gpu_enabled: true
              gpu_memory_gb: 80
              availability_zone: az-2
            
            hx-ollama-prod-03.hana-x.ai:
              ansible_host: 10.0.2.22
              server_role: ollama_tertiary
              services: ['ollama', 'specialized_models', 'overflow_capacity']
              os_type: linux
              memory_gb: 64
              cpu_cores: 32
              gpu_enabled: true
              gpu_memory_gb: 80
              availability_zone: az-1
        
        model_storage:
          hosts:
            hx-models-prod-01.hana-x.ai:
              ansible_host: 10.0.2.30
              server_role: model_repository_primary
              services: ['model_storage', 'version_control', 'model_registry', 'cdn']
              os_type: linux
              memory_gb: 16
              cpu_cores: 8
              storage_tb: 50
              availability_zone: az-1
            
            hx-models-prod-02.hana-x.ai:
              ansible_host: 10.0.2.31
              server_role: model_repository_replica
              services: ['model_storage', 'backup', 'disaster_recovery']
              os_type: linux
              memory_gb: 16
              cpu_cores: 8
              storage_tb: 50
              availability_zone: az-2
    
    # UI Services Group (High Availability Web Tier)
    ui:
      children:
        web_interfaces:
          hosts:
            hx-webui-prod-01.hana-x.ai:
              ansible_host: 10.0.3.10
              server_role: webui_primary
              services: ['chat_interface', 'admin_panel', 'user_management', 'analytics']
              os_type: linux
              memory_gb: 16
              cpu_cores: 8
              availability_zone: az-1
            
            hx-webui-prod-02.hana-x.ai:
              ansible_host: 10.0.3.11
              server_role: webui_secondary
              services: ['chat_interface', 'load_balancing', 'failover']
              os_type: linux
              memory_gb: 16
              cpu_cores: 8
              availability_zone: az-2
            
            hx-webui-prod-03.hana-x.ai:
              ansible_host: 10.0.3.12
              server_role: webui_tertiary
              services: ['chat_interface', 'auto_scaling', 'peak_load_handling']
              os_type: linux
              memory_gb: 16
              cpu_cores: 8
              availability_zone: az-1
        
        load_balancers:
          hosts:
            hx-lb-prod-01.hana-x.ai:
              ansible_host: 10.0.3.20
              server_role: primary_load_balancer
              services: ['nginx', 'ssl_termination', 'traffic_routing', 'waf']
              os_type: linux
              memory_gb: 8
              cpu_cores: 4
              keepalived_priority: 110
              vip_address: 10.0.3.100
              availability_zone: az-1
            
            hx-lb-prod-02.hana-x.ai:
              ansible_host: 10.0.3.21
              server_role: secondary_load_balancer
              services: ['nginx', 'ssl_termination', 'failover', 'waf']
              os_type: linux
              memory_gb: 8
              cpu_cores: 4
              keepalived_priority: 100
              vip_address: 10.0.3.100
              availability_zone: az-2
    
    # Operations Services Group (Enterprise Grade)
    operations:
      children:
        databases:
          hosts:
            hx-db-prod-01.hana-x.ai:
              ansible_host: 10.0.4.10
              server_role: postgresql_master
              services: ['postgresql', 'user_data', 'chat_history', 'analytics', 'backup']
              os_type: linux
              memory_gb: 32
              cpu_cores: 16
              storage_gb: 2000
              postgresql_role: master
              availability_zone: az-1
            
            hx-db-prod-02.hana-x.ai:
              ansible_host: 10.0.4.11
              server_role: postgresql_replica_1
              services: ['postgresql', 'read_replica', 'reporting', 'analytics']
              os_type: linux
              memory_gb: 32
              cpu_cores: 16
              storage_gb: 2000
              postgresql_role: replica
              availability_zone: az-2
            
            hx-db-prod-03.hana-x.ai:
              ansible_host: 10.0.4.12
              server_role: postgresql_replica_2
              services: ['postgresql', 'read_replica', 'backup_target']
              os_type: linux
              memory_gb: 32
              cpu_cores: 16
              storage_gb: 2000
              postgresql_role: replica
              availability_zone: az-1
        
        cache_services:
          hosts:
            hx-redis-prod-01.hana-x.ai:
              ansible_host: 10.0.4.20
              server_role: redis_master
              services: ['redis', 'session_cache', 'api_cache', 'rate_limiting', 'pub_sub']
              os_type: linux
              memory_gb: 16
              cpu_cores: 8
              redis_role: master
              availability_zone: az-1
            
            hx-redis-prod-02.hana-x.ai:
              ansible_host: 10.0.4.21
              server_role: redis_replica_1
              services: ['redis', 'cache_replica', 'failover']
              os_type: linux
              memory_gb: 16
              cpu_cores: 8
              redis_role: replica
              availability_zone: az-2
            
            hx-redis-prod-03.hana-x.ai:
              ansible_host: 10.0.4.22
              server_role: redis_replica_2
              services: ['redis', 'cache_replica', 'disaster_recovery']
              os_type: linux
              memory_gb: 16
              cpu_cores: 8
              redis_role: replica
              availability_zone: az-1
        
        monitoring:
          hosts:
            hx-monitor-prod-01.hana-x.ai:
              ansible_host: 10.0.5.10
              server_role: monitoring_primary
              services: ['prometheus', 'grafana', 'alertmanager', 'node_exporter', 'blackbox_exporter']
              os_type: linux
              memory_gb: 16
              cpu_cores: 8
              storage_gb: 1000
              availability_zone: az-1
            
            hx-monitor-prod-02.hana-x.ai:
              ansible_host: 10.0.5.11
              server_role: monitoring_secondary
              services: ['prometheus', 'grafana', 'failover', 'disaster_recovery']
              os_type: linux
              memory_gb: 16
              cpu_cores: 8
              storage_gb: 1000
              availability_zone: az-2
        
        logging:
          hosts:
            hx-logs-prod-01.hana-x.ai:
              ansible_host: 10.0.5.20
              server_role: logging_primary
              services: ['elasticsearch', 'logstash', 'kibana', 'filebeat', 'security_logs']
              os_type: linux
              memory_gb: 24
              cpu_cores: 12
              storage_gb: 5000
              availability_zone: az-1
            
            hx-logs-prod-02.hana-x.ai:
              ansible_host: 10.0.5.21
              server_role: logging_secondary
              services: ['elasticsearch', 'logstash', 'cluster_node', 'replication']
              os_type: linux
              memory_gb: 24
              cpu_cores: 12
              storage_gb: 5000
              availability_zone: az-2

  vars:
    # Global Production Environment Variables
    environment: production
    domain_name: hana-x.ai
    network_subnet: 10.0.0.0/16
    
    # Authentication Configuration
    ansible_user: agent0
    ansible_ssh_user: agent0
    admin_email: agent0@hana-x.ai
    
    # SSH Configuration (Production Security)
    ansible_ssh_private_key_file: ~/.ssh/hx_infrastructure_prod
    ansible_ssh_common_args: '-o StrictHostKeyChecking=yes -o UserKnownHostsFile=~/.ssh/known_hosts'
    
    # Common Service Configuration
    timezone: UTC
    ntp_servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org
      - 3.pool.ntp.org
    
    # Security Configuration (Production Hardened)
    firewall_enabled: true
    fail2ban_enabled: true
    automatic_updates: true
    security_hardening: true
    intrusion_detection: true
    
    # Backup Configuration (Enterprise)
    backup_enabled: true
    backup_retention_days: 365
    backup_schedule: "0 1 * * *"  # Daily at 1 AM
    disaster_recovery_enabled: true
    cross_region_backup: true
    
    # Monitoring Configuration (Comprehensive)
    monitoring_enabled: true
    log_level: warn
    metrics_retention_days: 365
    alerting_enabled: true
    sla_monitoring: true
    
    # Production Specific Settings
    debug_mode: false
    ssl_verification: true
    high_availability: true
    auto_scaling: true
    performance_optimization: true
    
    # Performance Configuration
    max_connections: 10000
    connection_timeout: 30
    read_timeout: 60
    write_timeout: 60
    
    # SSL/TLS Configuration
    ssl_protocols: ['TLSv1.2', 'TLSv1.3']
    ssl_ciphers: 'ECDHE+AESGCM:ECDHE+CHACHA20:DHE+AESGCM:DHE+CHACHA20:!aNULL:!MD5:!DSS'
    hsts_enabled: true
    
    # Compliance and Auditing
    audit_logging: true
    compliance_monitoring: true
    gdpr_compliance: true
    data_retention_policy: true

# Service-specific groupings for production operations
production_infrastructure:
  children:
    domain_controllers:
    certificate_authorities:

production_ai_ml:
  children:
    llm_gateways:
    llm_inference:
    model_storage:

production_ui:
  children:
    web_interfaces:
    load_balancers:

production_operations:
  children:
    databases:
    cache_services:
    monitoring:
    logging:

# High Availability Groupings
primary_services:
  hosts:
    hx-dc-prod-01.hana-x.ai:
    hx-ca-prod-01.hana-x.ai:
    hx-litellm-prod-01.hana-x.ai:
    hx-ollama-prod-01.hana-x.ai:
    hx-webui-prod-01.hana-x.ai:
    hx-lb-prod-01.hana-x.ai:
    hx-db-prod-01.hana-x.ai:
    hx-redis-prod-01.hana-x.ai:
    hx-monitor-prod-01.hana-x.ai:
    hx-logs-prod-01.hana-x.ai:

secondary_services:
  hosts:
    hx-dc-prod-02.hana-x.ai:
    hx-ca-prod-02.hana-x.ai:
    hx-litellm-prod-02.hana-x.ai:
    hx-ollama-prod-02.hana-x.ai:
    hx-webui-prod-02.hana-x.ai:
    hx-lb-prod-02.hana-x.ai:
    hx-db-prod-02.hana-x.ai:
    hx-redis-prod-02.hana-x.ai:
    hx-monitor-prod-02.hana-x.ai:
    hx-logs-prod-02.hana-x.ai:

# Availability Zone Groupings
availability_zone_1:
  hosts:
    hx-dc-prod-01.hana-x.ai:
    hx-ca-prod-01.hana-x.ai:
    hx-litellm-prod-01.hana-x.ai:
    hx-ollama-prod-01.hana-x.ai:
    hx-ollama-prod-03.hana-x.ai:
    hx-models-prod-01.hana-x.ai:
    hx-webui-prod-01.hana-x.ai:
    hx-webui-prod-03.hana-x.ai:
    hx-lb-prod-01.hana-x.ai:
    hx-db-prod-01.hana-x.ai:
    hx-db-prod-03.hana-x.ai:
    hx-redis-prod-01.hana-x.ai:
    hx-redis-prod-03.hana-x.ai:
    hx-monitor-prod-01.hana-x.ai:
    hx-logs-prod-01.hana-x.ai:

availability_zone_2:
  hosts:
    hx-dc-prod-02.hana-x.ai:
    hx-ca-prod-02.hana-x.ai:
    hx-litellm-prod-02.hana-x.ai:
    hx-ollama-prod-02.hana-x.ai:
    hx-models-prod-02.hana-x.ai:
    hx-webui-prod-02.hana-x.ai:
    hx-lb-prod-02.hana-x.ai:
    hx-db-prod-02.hana-x.ai:
    hx-redis-prod-02.hana-x.ai:
    hx-monitor-prod-02.hana-x.ai:
    hx-logs-prod-02.hana-x.ai:

# GPU-enabled hosts for AI/ML workloads
gpu_enabled_hosts:
  hosts:
    hx-litellm-prod-01.hana-x.ai:
    hx-litellm-prod-02.hana-x.ai:
    hx-ollama-prod-01.hana-x.ai:
    hx-ollama-prod-02.hana-x.ai:
    hx-ollama-prod-03.hana-x.ai:

# Critical services requiring immediate attention
critical_services:
  hosts:
    hx-db-prod-01.hana-x.ai:
    hx-redis-prod-01.hana-x.ai:
    hx-lb-prod-01.hana-x.ai:
    hx-lb-prod-02.hana-x.ai:
    hx-ollama-prod-01.hana-x.ai:
    hx-litellm-prod-01.hana-x.ai:
