---

---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  pre_tasks:
    - name: Update package cache (Ubuntu/Debian)
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update package cache (CentOS/RHEL)
      yum:
        update_cache: true
      when: ansible_os_family == "RedHat"

  tasks:
    - name: Install basic packages
      package:
        name:
          - curl
          - wget
          - git
          - vim
        state: present

    - name: Create test user
      user:
        name: testuser
        shell: /bin/bash
        create_home: true
        state: present

    - name: Ensure service is running (systemd)
      systemd:
        name: ssh
        state: started
        enabled: true
      when: ansible_service_mgr == "systemd"

    - name: Test idempotency marker
      file:
        path: /tmp/molecule-test
        state: touch
        mode: '0644'

