---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-ubuntu-20
    image: quay.io/ansible/molecule-ubuntu:20.04
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/lib/systemd/systemd"
    tmpfs:
      - /run
      - /tmp
  - name: instance-ubuntu-22
    image: quay.io/ansible/molecule-ubuntu:22.04
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/lib/systemd/systemd"
    tmpfs:
      - /run
      - /tmp
  - name: instance-centos-8
    image: quay.io/ansible/molecule-centos:8
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/lib/systemd/systemd"
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
  inventory:
    host_vars:
      instance-ubuntu-20:
        ansible_user: root
      instance-ubuntu-22:
        ansible_user: root
      instance-centos-8:
        ansible_user: root
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

