
---
# PostgreSQL Authentication Configuration
hx_pg_auth_method: "scram-sha-256"
hx_pg_password_encryption: "scram-sha-256"

# SSL/TLS Configuration
hx_pg_ssl_enabled: true
hx_pg_ssl_cert_file: "/etc/ssl/certs/postgresql.crt"
hx_pg_ssl_key_file: "/etc/ssl/private/postgresql.key"
hx_pg_ssl_ca_file: "/etc/ssl/certs/ca.crt"
hx_pg_ssl_crl_file: ""
hx_pg_ssl_ciphers: "HIGH:MEDIUM:+3DES:!aNULL"
hx_pg_ssl_prefer_server_ciphers: true

# Connection Configuration
hx_pg_listen_addresses: "localhost"
hx_pg_port: 5432
hx_pg_max_connections: 200
hx_pg_superuser_reserved_connections: 3

# Authentication and Access Control
hx_pg_users: []
# Example:
# hx_pg_users:
#   - name: "app_user"
#     password: "{{ vault_password | default('CHANGE_ME_VAULT_REQUIRED') }}" vault_app_user_password | default('CHANGE_ME_VAULT_REQUIRED') }}"
#     role_attr_flags: "CREATEDB,NOSUPERUSER"
#     db: "application_db"
#     priv: "ALL"

hx_pg_databases: []
# Example:
# hx_pg_databases:
#   - name: "application_db"
#     owner: "app_user"
#     encoding: "UTF8"
#     lc_collate: "en_US.UTF-8"
#     lc_ctype: "en_US.UTF-8"

# HBA Configuration
hx_pg_hba_entries:
  - type: "local"
    database: "all"
    user: "postgres"
    auth_method: "peer"
  - type: "local"
    database: "all"
    user: "all"
    auth_method: "peer"
  - type: "host"
    database: "all"
    user: "all"
    address: "127.0.0.1/32"
    auth_method: "{{ hx_pg_auth_method }}"
  - type: "host"
    database: "all"
    user: "all"
    address: "::1/128"
    auth_method: "{{ hx_pg_auth_method }}"

# Security Configuration
hx_pg_log_connections: true
hx_pg_log_disconnections: true
hx_pg_log_failed_connections: true
hx_pg_log_hostname: false
hx_pg_log_line_prefix: "%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h "

# Performance and Monitoring
hx_pg_shared_preload_libraries: "pg_stat_statements"
hx_pg_track_activities: true
hx_pg_track_counts: true
hx_pg_track_functions: "all"

# Backup Configuration
hx_pg_backup_user: "backup_user"
hx_pg_backup_password: "{{ vault_password | default('CHANGE_ME_VAULT_REQUIRED') }}" vault_backup_password | default('CHANGE_ME_VAULT_REQUIRED') }}"

# Service Management
hx_pg_service_name: "postgresql"
hx_pg_service_enabled: true
hx_pg_service_state: "started"

# File Paths
hx_pg_config_dir: "/etc/postgresql/14/main"
hx_pg_data_dir: "/var/lib/postgresql/14/main"
hx_pg_log_dir: "/var/log/postgresql"

# Validation Settings
hx_pg_validate_config: true
hx_pg_backup_config: true
hx_pg_restart_on_change: true
