---
# PostgreSQL Authentication Role - Default Variables
# HX Infrastructure Ansible - Enterprise Grade Configuration

# ------------------------------------------------------------------------------
# POSTGRESQL INSTALLATION SETTINGS
# ------------------------------------------------------------------------------
hx_pg_version: "15"
hx_pg_packages:
  - postgresql-{{ hx_pg_version }}
  - postgresql-{{ hx_pg_version }}-contrib
  - python3-psycopg2
  - postgresql-client-{{ hx_pg_version }}

# ------------------------------------------------------------------------------
# POSTGRESQL DIRECTORIES AND PATHS
# ------------------------------------------------------------------------------
hx_pg_data_directory: "/var/lib/postgresql/{{ hx_pg_version }}/main"
hx_pg_config_directory: "/etc/postgresql/{{ hx_pg_version }}/main"
hx_pg_log_directory: "/var/log/postgresql"
hx_pg_backup_directory: "/var/lib/postgresql/backups"
hx_pg_archive_directory: "/var/lib/postgresql/archive"

# ------------------------------------------------------------------------------
# CONNECTION AND AUTHENTICATION SETTINGS
# ------------------------------------------------------------------------------
hx_pg_listen_addresses: "127.0.0.1"  # Security: Only localhost by default
hx_pg_port: 5432
hx_pg_max_connections: 100
hx_pg_superuser_reserved_connections: 3

# Authentication methods
hx_pg_local_auth_method: "md5"
hx_pg_allow_local_connections: true
hx_pg_reject_other_connections: true

# ------------------------------------------------------------------------------
# SSL/TLS CONFIGURATION
# ------------------------------------------------------------------------------
hx_pg_enable_ssl: true
hx_pg_ssl_cert_file: "server.crt"
hx_pg_ssl_key_file: "server.key"
hx_pg_ssl_ca_file: ""

# ------------------------------------------------------------------------------
# RESOURCE USAGE SETTINGS
# ------------------------------------------------------------------------------
hx_pg_shared_buffers: "128MB"
hx_pg_huge_pages: "try"
hx_pg_temp_buffers: "8MB"
hx_pg_max_prepared_transactions: 0
hx_pg_work_mem: "4MB"

# ------------------------------------------------------------------------------
# WRITE AHEAD LOG (WAL) SETTINGS
# ------------------------------------------------------------------------------
hx_pg_wal_level: "replica"
hx_pg_fsync: true
hx_pg_synchronous_commit: "on"
hx_pg_wal_sync_method: "fsync"
hx_pg_full_page_writes: true
hx_pg_wal_buffers: "16MB"
hx_pg_wal_writer_delay: "200ms"
hx_pg_checkpoint_completion_target: 0.5
hx_pg_max_wal_size: "1GB"
hx_pg_min_wal_size: "80MB"

# WAL Archiving
hx_pg_enable_wal_archiving: false
hx_pg_archive_command: "test ! -f {{ hx_pg_archive_directory }}/%f && cp %p {{ hx_pg_archive_directory }}/%f"

# ------------------------------------------------------------------------------
# REPLICATION SETTINGS
# ------------------------------------------------------------------------------
hx_pg_max_wal_senders: 10
hx_pg_max_replication_slots: 10
hx_pg_wal_keep_segments: 32
hx_pg_hot_standby: true

# ------------------------------------------------------------------------------
# LOGGING CONFIGURATION
# ------------------------------------------------------------------------------
hx_pg_log_destination: "stderr"
hx_pg_logging_collector: true
hx_pg_log_filename: "postgresql-%Y-%m-%d_%H%M%S.log"
hx_pg_log_file_mode: "0600"
hx_pg_log_truncate_on_rotation: false
hx_pg_log_rotation_age: "1d"
hx_pg_log_rotation_size: "10MB"

# What to log
hx_pg_log_min_messages: "warning"
hx_pg_log_min_error_statement: "error"
hx_pg_log_min_duration_statement: -1
hx_pg_log_checkpoints: false
hx_pg_log_connections: false
hx_pg_log_disconnections: false
hx_pg_log_lock_waits: false
hx_pg_log_statement: "none"
hx_pg_log_temp_files: -1

# ------------------------------------------------------------------------------
# STATISTICS AND MONITORING
# ------------------------------------------------------------------------------
hx_pg_track_activities: true
hx_pg_track_counts: true
hx_pg_track_io_timing: false
hx_pg_track_functions: "none"
hx_pg_track_activity_query_size: 1024
hx_pg_stats_temp_directory: "pg_stat_tmp"

# ------------------------------------------------------------------------------
# AUTOVACUUM SETTINGS
# ------------------------------------------------------------------------------
hx_pg_autovacuum: true
hx_pg_log_autovacuum_min_duration: -1
hx_pg_autovacuum_max_workers: 3
hx_pg_autovacuum_naptime: "1min"
hx_pg_autovacuum_vacuum_threshold: 50
hx_pg_autovacuum_analyze_threshold: 50
hx_pg_autovacuum_vacuum_scale_factor: 0.2
hx_pg_autovacuum_analyze_scale_factor: 0.1

# ------------------------------------------------------------------------------
# CLIENT CONNECTION DEFAULTS
# ------------------------------------------------------------------------------
hx_pg_search_path: '"$user", public'
hx_pg_default_tablespace: ""
hx_pg_temp_tablespaces: ""
hx_pg_check_function_bodies: true
hx_pg_default_transaction_isolation: "read committed"
hx_pg_default_transaction_read_only: false
hx_pg_default_transaction_deferrable: false
hx_pg_session_replication_role: "origin"
hx_pg_statement_timeout: 0
hx_pg_lock_timeout: 0
hx_pg_idle_in_transaction_session_timeout: 0

# ------------------------------------------------------------------------------
# LOCK MANAGEMENT
# ------------------------------------------------------------------------------
hx_pg_deadlock_timeout: "1s"
hx_pg_max_locks_per_transaction: 64
hx_pg_max_pred_locks_per_transaction: 64

# ------------------------------------------------------------------------------
# DATABASE AND USER MANAGEMENT
# ------------------------------------------------------------------------------
# Example database configuration
hx_pg_databases: []
# - name: "hx_app"
#   owner: "hx_user"
#   encoding: "UTF8"
#   lc_collate: "en_US.UTF-8"
#   lc_ctype: "en_US.UTF-8"

# Example user configuration (passwords should be vaulted)
hx_pg_users: []
# - name: "hx_user"
#   password: "{{ vault_hx_user_password }}"
#   db: "hx_app"
#   privileges: "ALL"
#   role_flags: "NOSUPERUSER,NOCREATEDB"

# Example privilege configuration
hx_pg_privileges: []
# - database: "hx_app"
#   role: "hx_user"
#   privileges: "ALL"
#   type: "database"
#   grant_option: false

# ------------------------------------------------------------------------------
# HBA (HOST-BASED AUTHENTICATION) ENTRIES
# ------------------------------------------------------------------------------
hx_pg_hba_entries: []
# Example entries:
# - type: "host"
#   database: "hx_app"
#   user: "hx_user"
#   address: "10.0.0.0/8"
#   method: "md5"
#   comment: "Application server access"

hx_pg_replication_connections: []
# Example replication entries:
# - type: "host"
#   user: "replicator"
#   address: "10.0.0.100/32"
#   method: "md5"
#   comment: "Standby server replication"

hx_pg_ssl_connections: []
# Example SSL entries:
# - database: "hx_app"
#   user: "hx_user"
#   address: "10.0.0.0/8"
#   method: "md5"
#   comment: "SSL required connection"

hx_pg_no_ssl_connections: []
# Example non-SSL entries (use with caution):
# - database: "hx_app"
#   user: "hx_user"
#   address: "192.168.1.0/24"
#   method: "md5"
#   comment: "Internal network non-SSL"

# ------------------------------------------------------------------------------
# BACKUP CONFIGURATION
# ------------------------------------------------------------------------------
hx_pg_enable_automated_backup: true
hx_pg_backup_databases: ["all"]  # "all" for pg_dumpall, or list specific databases
hx_pg_backup_retention_days: 7
hx_pg_backup_minute: "0"
hx_pg_backup_hour: "2"
# hx_pg_backup_notification_email: "admin@example.com"  # Uncomment to enable email notifications

# ------------------------------------------------------------------------------
# CONNECTION POOLING (PGBOUNCER)
# ------------------------------------------------------------------------------
hx_pg_enable_connection_pooling: false
hx_pg_pgbouncer_port: 6432
hx_pg_pgbouncer_pool_mode: "session"
hx_pg_pgbouncer_max_client_conn: 100
hx_pg_pgbouncer_default_pool_size: 20

# ------------------------------------------------------------------------------
# HEALTH CHECK CONFIGURATION
# ------------------------------------------------------------------------------
hx_pg_health_warning_threshold: 80
hx_pg_health_critical_threshold: 95
hx_pg_health_check_interval: "*/5 * * * *"  # Every 5 minutes

# ------------------------------------------------------------------------------
# SECURITY HARDENING SETTINGS
# ------------------------------------------------------------------------------
hx_pg_enable_security_hardening: true
hx_pg_disable_superuser_login: false
hx_pg_enable_row_security: true
hx_pg_log_security_events: true

# CIS Benchmark compliance settings
hx_pg_cis_compliance: true
hx_pg_cis_log_connections: true
hx_pg_cis_log_disconnections: true
hx_pg_cis_log_duration: true
hx_pg_cis_log_hostname: true
hx_pg_cis_log_line_prefix: "%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h "

# ------------------------------------------------------------------------------
# PERFORMANCE TUNING
# ------------------------------------------------------------------------------
hx_pg_enable_performance_tuning: false
hx_pg_random_page_cost: 1.1
hx_pg_effective_cache_size: "1GB"
hx_pg_effective_io_concurrency: 200

# ------------------------------------------------------------------------------
# MONITORING AND ALERTING
# ------------------------------------------------------------------------------
hx_pg_enable_monitoring: true
hx_pg_monitoring_user: "hx_monitor"
# hx_pg_monitoring_password: "{{ vault_hx_monitor_password }}"  # Should be vaulted

# ------------------------------------------------------------------------------
# EXTENSION MANAGEMENT
# ------------------------------------------------------------------------------
hx_pg_extensions: []
# Example extensions:
# - name: "pg_stat_statements"
#   database: "postgres"
# - name: "uuid-ossp"
#   database: "hx_app"

# ------------------------------------------------------------------------------
# MAINTENANCE SETTINGS
# ------------------------------------------------------------------------------
hx_pg_vacuum_cost_delay: "0"
hx_pg_vacuum_cost_limit: "200"
hx_pg_bgwriter_delay: "200ms"
hx_pg_bgwriter_lru_maxpages: "100"
hx_pg_bgwriter_lru_multiplier: "2.0"

# ------------------------------------------------------------------------------
# COMPATIBILITY AND VERSION SETTINGS
# ------------------------------------------------------------------------------
hx_pg_array_nulls: true
hx_pg_backslash_quote: "safe_encoding"
hx_pg_default_with_oids: false
hx_pg_escape_string_warning: true
hx_pg_lo_compat_privileges: false
hx_pg_operator_precedence_warning: false
hx_pg_quote_all_identifiers: false
hx_pg_sql_inheritance: true
hx_pg_standard_conforming_strings: true
hx_pg_synchronize_seqscans: true
hx_pg_transform_null_equals: false

# ------------------------------------------------------------------------------
# ERROR HANDLING
# ------------------------------------------------------------------------------
hx_pg_exit_on_error: false
hx_pg_restart_after_crash: true

# ------------------------------------------------------------------------------
# CUSTOM CONFIGURATION INCLUDES
# ------------------------------------------------------------------------------
# hx_pg_include_dir: "/etc/postgresql/conf.d"
# hx_pg_include_if_exists: "/etc/postgresql/local.conf"
# hx_pg_include_tasks: "/etc/postgresql/custom.conf"
