---
galaxy_info:
  author: HX Infrastructure Team
  description: Standardized LiteLLM Proxy installation with enhanced security and validation
  company: Hanax AI
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - "20.04"
        - "22.04"
        - "24.04"
  galaxy_tags:
    - litellm
    - proxy
    - llm
    - ai
    - standardized

dependencies: []

collections:
  - community.general
  - ansible.posix
  - community.postgresql
