
---
# Development environment inventory
# Following Ansible inventory best practices

all:
  children:
    dev_servers:
      hosts:
        dev-web-01.dev-test.hana-x.ai:
          ansible_host: 10.0.1.10
          server_role: web
          env_name: dev
        dev-app-01.dev-test.hana-x.ai:
          ansible_host: 10.0.1.11
          server_role: application
          env_name: dev
        dev-db-01.dev-test.hana-x.ai:
          ansible_host: 10.0.1.12
          server_role: database
          env_name: dev
      vars:
        ansible_user: agent0
        ansible_become: true
        ansible_become_method: sudo
        environment_type: development
        backup_enabled: true
        monitoring_enabled: true

    backup_servers:
      hosts:
        dev-backup-01.dev-test.hana-x.ai:
          ansible_host: 10.0.1.20
          server_role: backup
          env_name: dev
      vars:
        ansible_user: agent0
        backup_retention_days: 7

  vars:
    # Global variables for dev environment
    domain_name: dev-test.hana-x.ai
    ntp_servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
    dns_servers:
      - 8.8.8.8
      - 8.8.4.4
