---
# DEPRECATION WARNING: This inventory uses legacy 10.0.1.x IP addresses
# Production infrastructure uses 192.168.10.x range
# This inventory is for development/testing only
# DO NOT USE FOR PRODUCTION DEPLOYMENTS

all:
  children:
    web_servers:
      hosts:
        web01:
          ansible_host: 10.0.1.10
          server_role: web
        web02:
          ansible_host: 10.0.1.11
          server_role: web
        web03:
          ansible_host: 10.0.1.12
          server_role: web
      vars:
        http_port: 80
        https_port: 443
        max_clients: 200

    database_servers:
      hosts:
        db01:
          ansible_host: 10.0.1.20
          server_role: database
          db_type: postgresql
      vars:
        db_port: 5432
        max_connections: 100

    load_balancers:
      hosts:
        lb01:
          ansible_host: 10.0.1.30
          server_role: load_balancer
      vars:
        lb_algorithm: round_robin
        health_check_interval: 30

  vars:
    # Global development environment variables
    ansible_user: agent0
    ansible_become: true
    ansible_become_method: sudo
    environment_type: development
    domain_name: dev.hana-x.ai

    # Development-specific SSH configuration (secure)
    ansible_ssh_common_args: '-o StrictHostKeyChecking=yes -o UserKnownHostsFile=~/.ssh/known_hosts_dev -o IdentitiesOnly=yes'
    ansible_ssh_pipelining: true
    ansible_connection_timeout: 30
    ansible_command_timeout: 300

    # Development monitoring and backup settings
    backup_enabled: false
    monitoring_enabled: true
    log_level: debug

    # Development security settings
    firewall_enabled: false
    selinux_enabled: false
    fail2ban_enabled: false
