
# HX Infrastructure Development Environment Inventory
# Domain: dev-test.hana-x.ai
# Network: 192.168.10.0/24
# Authentication: agent0 user (agent0@hana-x.ai)

all:
  children:
    # Infrastructure Services Group
    infrastructure:
      children:
        domain_controllers:
          hosts:
            hx-dc-01.dev-test.hana-x.ai:
              ansible_host: 192.168.10.10
              server_role: primary_domain_controller
              services: ['active_directory', 'dns', 'dhcp']
              os_type: windows_server
              memory_gb: 8
              cpu_cores: 4
        
        certificate_authorities:
          hosts:
            hx-ca-01.dev-test.hana-x.ai:
              ansible_host: 192.168.10.11
              server_role: certificate_authority
              services: ['pki', 'ssl_certificates', 'code_signing']
              os_type: windows_server
              memory_gb: 4
              cpu_cores: 2
    
    # AI/ML Services Group
    ai_ml:
      children:
        llm_services:
          hosts:
            hx-litellm-01.dev-test.hana-x.ai:
              ansible_host: 192.168.10.20
              server_role: litellm_gateway
              services: ['litellm', 'api_gateway', 'model_routing']
              os_type: linux
              memory_gb: 16
              cpu_cores: 8
              gpu_enabled: true
            
            hx-ollama-01.dev-test.hana-x.ai:
              ansible_host: 192.168.10.21
              server_role: ollama_primary
              services: ['ollama', 'llama_models', 'local_inference']
              os_type: linux
              memory_gb: 32
              cpu_cores: 16
              gpu_enabled: true
              gpu_memory_gb: 24
            
            hx-ollama-02.dev-test.hana-x.ai:
              ansible_host: 192.168.10.22
              server_role: ollama_secondary
              services: ['ollama', 'model_backup', 'load_balancing']
              os_type: linux
              memory_gb: 32
              cpu_cores: 16
              gpu_enabled: true
              gpu_memory_gb: 24
        
        model_storage:
          hosts:
            hx-models-01.dev-test.hana-x.ai:
              ansible_host: 192.168.10.23
              server_role: model_repository
              services: ['model_storage', 'version_control', 'model_registry']
              os_type: linux
              memory_gb: 8
              cpu_cores: 4
              storage_tb: 10
    
    # UI Services Group
    ui:
      children:
        web_interfaces:
          hosts:
            hx-webui-01.dev-test.hana-x.ai:
              ansible_host: 192.168.10.30
              server_role: primary_webui
              services: ['chat_interface', 'admin_panel', 'user_management']
              os_type: linux
              memory_gb: 8
              cpu_cores: 4
            
            hx-webui-02.dev-test.hana-x.ai:
              ansible_host: 192.168.10.31
              server_role: secondary_webui
              services: ['chat_interface', 'load_balancing', 'failover']
              os_type: linux
              memory_gb: 8
              cpu_cores: 4
        
        load_balancers:
          hosts:
            hx-lb-01.dev-test.hana-x.ai:
              ansible_host: 192.168.10.32
              server_role: primary_load_balancer
              services: ['nginx', 'ssl_termination', 'traffic_routing']
              os_type: linux
              memory_gb: 4
              cpu_cores: 2
              keepalived_priority: 110
              vip_address: 192.168.10.100
    
    # Operations Services Group
    operations:
      children:
        databases:
          hosts:
            hx-db-01.dev-test.hana-x.ai:
              ansible_host: 192.168.10.40
              server_role: postgresql_primary
              services: ['postgresql', 'user_data', 'chat_history', 'system_config']
              os_type: linux
              memory_gb: 16
              cpu_cores: 8
              storage_gb: 500
              postgresql_role: master
            
            hx-db-02.dev-test.hana-x.ai:
              ansible_host: 192.168.10.41
              server_role: postgresql_replica
              services: ['postgresql', 'read_replica', 'backup_target']
              os_type: linux
              memory_gb: 16
              cpu_cores: 8
              storage_gb: 500
              postgresql_role: replica
        
        cache_services:
          hosts:
            hx-redis-01.dev-test.hana-x.ai:
              ansible_host: 192.168.10.42
              server_role: redis_primary
              services: ['redis', 'session_cache', 'api_cache', 'rate_limiting']
              os_type: linux
              memory_gb: 8
              cpu_cores: 4
              redis_role: master
            
            hx-redis-02.dev-test.hana-x.ai:
              ansible_host: 192.168.10.43
              server_role: redis_replica
              services: ['redis', 'cache_replica', 'failover']
              os_type: linux
              memory_gb: 8
              cpu_cores: 4
              redis_role: replica
        
        monitoring:
          hosts:
            hx-monitor-01.dev-test.hana-x.ai:
              ansible_host: 192.168.10.50
              server_role: monitoring_server
              services: ['prometheus', 'grafana', 'alertmanager', 'node_exporter']
              os_type: linux
              memory_gb: 8
              cpu_cores: 4
              storage_gb: 200
        
        logging:
          hosts:
            hx-logs-01.dev-test.hana-x.ai:
              ansible_host: 192.168.10.51
              server_role: logging_server
              services: ['elasticsearch', 'logstash', 'kibana', 'filebeat']
              os_type: linux
              memory_gb: 12
              cpu_cores: 6
              storage_gb: 1000

  vars:
    # Global Development Environment Variables
    environment: development
    domain_name: dev-test.hana-x.ai
    network_subnet: 192.168.10.0/24
    
    # Authentication Configuration
    ansible_user: agent0
    ansible_ssh_user: agent0
    admin_email: agent0@hana-x.ai
    
    # SSH Configuration
    ansible_ssh_private_key_file: ~/.ssh/hx_infrastructure_dev
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    
    # Common Service Configuration
    timezone: UTC
    ntp_servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
    
    # Security Configuration
    firewall_enabled: true
    fail2ban_enabled: true
    automatic_updates: true
    
    # Backup Configuration
    backup_enabled: true
    backup_retention_days: 30
    backup_schedule: "0 2 * * *"  # Daily at 2 AM
    
    # Monitoring Configuration
    monitoring_enabled: true
    log_level: info
    metrics_retention_days: 90
    
    # Development Specific Settings
    debug_mode: true
    ssl_verification: false
    development_tools: true
    test_data_enabled: true

# Service-specific groupings for targeted deployments
infrastructure_services:
  children:
    domain_controllers:
    certificate_authorities:

ai_ml_services:
  children:
    llm_services:
    model_storage:

ui_services:
  children:
    web_interfaces:
    load_balancers:

operations_services:
  children:
    databases:
    cache_services:
    monitoring:
    logging:

# Platform-specific groupings
linux_hosts:
  children:
    ai_ml:
    ui:
    operations:

windows_hosts:
  children:
    infrastructure:

# Role-specific groupings for maintenance
primary_services:
  hosts:
    hx-dc-01.dev-test.hana-x.ai:
    hx-litellm-01.dev-test.hana-x.ai:
    hx-ollama-01.dev-test.hana-x.ai:
    hx-webui-01.dev-test.hana-x.ai:
    hx-lb-01.dev-test.hana-x.ai:
    hx-db-01.dev-test.hana-x.ai:
    hx-redis-01.dev-test.hana-x.ai:

secondary_services:
  hosts:
    hx-ollama-02.dev-test.hana-x.ai:
    hx-webui-02.dev-test.hana-x.ai:
    hx-db-02.dev-test.hana-x.ai:
    hx-redis-02.dev-test.hana-x.ai:

gpu_enabled_hosts:
  hosts:
    hx-litellm-01.dev-test.hana-x.ai:
    hx-ollama-01.dev-test.hana-x.ai:
    hx-ollama-02.dev-test.hana-x.ai:
