---
# Canary Deployment Automation
- name: Canary Deployment Strategy
  hosts: "{{ target_environment | default('production') }}"
  become: true
  gather_facts: true
  vars:
    deployment_strategy: "canary"
    canary_percentage: "{{ canary_traffic_percentage | default(10) }}"
    monitoring_duration: "{{ canary_monitoring_time | default(600) }}"

  pre_tasks:
    - name: Validate canary deployment prerequisites
      ansible.builtin.include_role:
        name: production_ops
        tasks_from: validate_canary_prerequisites

  tasks:
    - name: Deploy to canary instances
      ansible.builtin.include_role:
        name: production_ops
        tasks_from: canary_deployment
      vars:
        canary_instances: "{{ groups['canary'] | default([]) }}"

    - name: Configure traffic routing
      ansible.builtin.include_role:
        name: production_ops
        tasks_from: configure_canary_routing

    - name: Monitor canary performance
      ansible.builtin.include_role:
        name: health_monitoring
        tasks_from: canary_monitoring
      vars:
        monitoring_duration: "{{ monitoring_duration }}"

    - name: Evaluate canary metrics
      ansible.builtin.include_role:
        name: production_ops
        tasks_from: evaluate_canary_metrics

    - name: Proceed with full deployment
      ansible.builtin.include_role:
        name: production_ops
        tasks_from: full_deployment
      when: canary_evaluation_passed | default(false)

  rescue:
    - name: Rollback canary deployment
      ansible.builtin.include_role:
        name: production_ops
        tasks_from: rollback_canary
