---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart intelligent monitoring
  systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - hx-anomaly-detector
    - hx-predictive-scaler
    - hx-cost-optimizer
    - hx-monitoring-dashboard
