
---
# HX CA Trust Role Default Variables
# Certificate Authority Trust Management

# Core Service Settings
hx_ca_trust_enabled: true
hx_ca_trust_version: "1.0.0"

# Certificate Authority Configuration
hx_ca_host: "hx-ca-server.dev-test.hana-x.ai"
hx_ca_root_ca_path_on_ca: "/home/agent0/easy-rsa/pki/ca.crt"
hx_ca_root_ca_filename: "hx-rootCA.crt"
hx_ca_local_cert_path: "/usr/local/share/ca-certificates/hx-root-ca.crt"

# Domain Controller Configuration
hx_ca_dc_host: "hx-dc-server.dev-test.hana-x.ai"
hx_ca_dc_report_dir: "/var/log/hx"

# Security Settings
hx_ca_security_enabled: true
hx_ca_expected_sha256: ""  # Optional SHA256 fingerprint validation
hx_ca_verify_chain: true
hx_ca_strict_permissions: true

# Certificate Validation Settings
hx_ca_validation_enabled: true
hx_ca_san_check_targets: []
hx_ca_health_checks_enabled: true

# File Permissions
hx_ca_cert_owner: "root"
hx_ca_cert_group: "root"
hx_ca_cert_mode: "0644"

# Package Management
hx_ca_packages:
  - ca-certificates
  - openssl

# Feature Flags
hx_ca_backup_enabled: true
hx_ca_monitoring_enabled: false
hx_ca_audit_logging_enabled: true

# Performance Settings
hx_ca_update_timeout: 30
hx_ca_validation_retries: 3
hx_ca_validation_delay: 5
