#!/bin/bash
# Phase 2B Baseline Capture Script
# Engineering-approved baseline capture for rollback capability

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASELINE_DIR="${SCRIPT_DIR}/tmp"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

# Create baseline directory if it doesn't exist
mkdir -p "${BASELINE_DIR}"

echo "=== Phase 2B Baseline Capture - ${TIMESTAMP} ==="

# Capture branch baseline
echo "Capturing branch baseline..."
git branch -a > "${BASELINE_DIR}/branch_baseline_${TIMESTAMP}.txt"

# Capture collections/roles baseline
echo "Capturing collections and roles baseline..."
{
    echo "# Ansible Collections and Roles Baseline - ${TIMESTAMP}"
    echo "# Generated by baseline_capture.sh"
    echo ""
    
    # Find all playbooks
    echo "## Playbooks:"
    find . -name "*.yml" -o -name "*.yaml" | grep -i playbook | sort || echo "No playbooks found"
    echo ""
    
    # Find all roles
    echo "## Roles:"
    find . -type d -name "roles" -exec find {} -mindepth 1 -maxdepth 1 -type d \; | sort || echo "No roles found"
    echo ""
    
    # Find all collections references
    echo "## Collections References:"
    find . -name "*.yml" -o -name "*.yaml" | xargs grep -l "collections:" 2>/dev/null | sort || echo "No collection references found"
    echo ""
    
    # Find all inventory files
    echo "## Inventory Files:"
    find . -name "inventory*" -o -name "hosts*" | sort || echo "No inventory files found"
    
} > "${BASELINE_DIR}/collections_baseline_${TIMESTAMP}.txt"

# Capture git status
echo "Capturing git status..."
git status --porcelain > "${BASELINE_DIR}/git_status_${TIMESTAMP}.txt"

# Capture commit hash
echo "Capturing current commit..."
git rev-parse HEAD > "${BASELINE_DIR}/commit_hash_${TIMESTAMP}.txt"

# Create summary
echo "Creating baseline summary..."
{
    echo "# Phase 2B Baseline Summary - ${TIMESTAMP}"
    echo "Generated: $(date)"
    echo "Branch: $(git branch --show-current)"
    echo "Commit: $(git rev-parse HEAD)"
    echo ""
    echo "## Files Generated:"
    echo "- branch_baseline_${TIMESTAMP}.txt"
    echo "- collections_baseline_${TIMESTAMP}.txt" 
    echo "- git_status_${TIMESTAMP}.txt"
    echo "- commit_hash_${TIMESTAMP}.txt"
    echo ""
    echo "## Branch Count:"
    echo "Total branches: $(git branch -a | wc -l)"
    echo "Local branches: $(git branch | wc -l)"
    echo "Remote branches: $(git branch -r | wc -l)"
} > "${BASELINE_DIR}/baseline_summary_${TIMESTAMP}.txt"

echo "✅ Baseline capture completed successfully!"
echo "📁 Files saved to: ${BASELINE_DIR}/"
echo "📊 Summary: baseline_summary_${TIMESTAMP}.txt"

# Return the timestamp for use by calling scripts
echo "${TIMESTAMP}"
