---

---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: cluster-test
    groups:
      - k8s_cluster
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
  inventory:
    group_vars:
      k8s_cluster:
        ansible_connection: kubectl
        ansible_kubectl_namespace: molecule-test
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
lint: |
  set -e
  yamllint .
  ansible-lint

