---
- name: Verify Cluster Deployment
  hosts: k8s_cluster
  connection: kubectl
  gather_facts: false
  tasks:
    - name: Verify namespace exists
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
        name: molecule-test
      register: namespace_info

    - name: Assert namespace is active
      assert:
        that:
          - namespace_info.resources | length > 0
          - namespace_info.resources[0].status.phase == "Active"
        fail_msg: "Test namespace is not active"
        success_msg: "Test namespace is active"

    - name: Verify pod is running
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        name: test-pod
        namespace: molecule-test
      register: pod_info

    - name: Assert pod is running
      assert:
        that:
          - pod_info.resources | length > 0
          - pod_info.resources[0].status.phase == "Running"
        fail_msg: "Test pod is not running"
        success_msg: "Test pod is running"

    - name: Verify service exists
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Service
        name: test-service
        namespace: molecule-test
      register: service_info

    - name: Assert service is configured
      assert:
        that:
          - service_info.resources | length > 0
          - service_info.resources[0].spec.ports[0].port == 80
        fail_msg: "Test service is not properly configured"
        success_msg: "Test service is properly configured"

