---
# HX Infrastructure - Shared IP Address Library
# Centralized IP address definitions for all environments
# Reference: https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#organizing-host-and-group-variables

# =============================================================================
# PRODUCTION ENVIRONMENT IP ADDRESSES
# =============================================================================
ip_addresses:
  production:
    # Network Subnets
    subnets:
      load_balancer: "10.0.1.0/24"
      web: "10.0.2.0/24"
      application: "10.0.3.0/24"
      database: "10.0.4.0/24"
      cache: "10.0.5.0/24"
      monitoring: "10.0.6.0/24"
      management: "10.0.10.0/24"
    
    # Gateway Addresses
    gateways:
      load_balancer: "10.0.1.1"
      web: "10.0.2.1"
      application: "10.0.3.1"
      database: "10.0.4.1"
      cache: "10.0.5.1"
      monitoring: "10.0.6.1"
      management: "10.0.10.1"
    
    # Load Balancer Tier
    load_balancer:
      hx-prod-lb-01: "10.0.1.10"
      hx-prod-lb-02: "10.0.1.11"
      vip: "10.0.1.100"
      keepalived_vip: "10.0.1.100"
    
    # Web Tier
    web:
      hx-prod-web-01: "10.0.2.10"
      hx-prod-web-02: "10.0.2.11"
      hx-prod-web-03: "10.0.2.12"
    
    # Application Tier
    application:
      hx-prod-app-01: "10.0.3.10"
      hx-prod-app-02: "10.0.3.11"
      hx-prod-app-03: "10.0.3.12"
    
    # Database Tier
    database:
      hx-prod-db-01: "10.0.4.10"
      hx-prod-db-02: "10.0.4.11"
      hx-prod-db-03: "10.0.4.12"
      cluster_vip: "10.0.4.100"
    
    # Cache Tier
    cache:
      hx-prod-cache-01: "10.0.5.10"
      hx-prod-cache-02: "10.0.5.11"
      cluster_vip: "10.0.5.100"
    
    # Monitoring Tier
    monitoring:
      hx-prod-monitor-01: "10.0.6.10"
      hx-prod-monitor-02: "10.0.6.11"
    
    # Management Network
    management:
      bastion: "10.0.10.10"
      ansible_controller: "10.0.10.11"
      backup_server: "10.0.10.12"

# =============================================================================
# STAGING ENVIRONMENT IP ADDRESSES
# =============================================================================
  staging:
    # Network Subnets
    subnets:
      load_balancer: "10.2.1.0/24"
      web: "10.2.2.0/24"
      application: "10.2.3.0/24"
      database: "10.2.4.0/24"
      cache: "10.2.5.0/24"
      monitoring: "10.2.6.0/24"
      management: "10.2.10.0/24"
    
    # Gateway Addresses
    gateways:
      load_balancer: "10.2.1.1"
      web: "10.2.2.1"
      application: "10.2.3.1"
      database: "10.2.4.1"
      cache: "10.2.5.1"
      monitoring: "10.2.6.1"
      management: "10.2.10.1"
    
    # Load Balancer Tier
    load_balancer:
      hx-stg-lb-01: "10.2.1.10"
      hx-stg-lb-02: "10.2.1.11"
      vip: "10.2.1.100"
      keepalived_vip: "10.2.1.100"
    
    # Web Tier
    web:
      hx-stg-web-01: "10.2.2.10"
      hx-stg-web-02: "10.2.2.11"
      hx-stg-web-03: "10.2.2.12"
    
    # Application Tier
    application:
      hx-stg-app-01: "10.2.3.10"
      hx-stg-app-02: "10.2.3.11"
      hx-stg-app-03: "10.2.3.12"
    
    # Database Tier
    database:
      hx-stg-db-01: "10.2.4.10"
      hx-stg-db-02: "10.2.4.11"
      hx-stg-db-03: "10.2.4.12"
      cluster_vip: "10.2.4.100"
    
    # Cache Tier
    cache:
      hx-stg-cache-01: "10.2.5.10"
      hx-stg-cache-02: "10.2.5.11"
      cluster_vip: "10.2.5.100"
    
    # Monitoring Tier
    monitoring:
      hx-stg-monitor-01: "10.2.6.10"
      hx-stg-monitor-02: "10.2.6.11"
    
    # Management Network
    management:
      bastion: "10.2.10.10"
      ansible_controller: "10.2.10.11"
      backup_server: "10.2.10.12"

# =============================================================================
# DEVELOPMENT ENVIRONMENT IP ADDRESSES
# =============================================================================
  development:
    # Network Subnets
    subnets:
      load_balancer: "10.1.1.0/24"
      web: "10.1.2.0/24"
      application: "10.1.3.0/24"
      database: "10.1.4.0/24"
      cache: "10.1.5.0/24"
      monitoring: "10.1.6.0/24"
      management: "10.1.10.0/24"
    
    # Gateway Addresses
    gateways:
      load_balancer: "10.1.1.1"
      web: "10.1.2.1"
      application: "10.1.3.1"
      database: "10.1.4.1"
      cache: "10.1.5.1"
      monitoring: "10.1.6.1"
      management: "10.1.10.1"
    
    # Load Balancer Tier
    load_balancer:
      hx-dev-lb-01: "10.1.1.10"
      hx-dev-lb-02: "10.1.1.11"
      vip: "10.1.1.100"
      keepalived_vip: "10.1.1.100"
    
    # Web Tier
    web:
      hx-dev-web-01: "10.1.2.10"
      hx-dev-web-02: "10.1.2.11"
    
    # Application Tier
    application:
      hx-dev-app-01: "10.1.3.10"
      hx-dev-app-02: "10.1.3.11"
    
    # Database Tier
    database:
      hx-dev-db-01: "10.1.4.10"
      hx-dev-db-02: "10.1.4.11"
      cluster_vip: "10.1.4.100"
    
    # Cache Tier
    cache:
      hx-dev-cache-01: "10.1.5.10"
      cluster_vip: "10.1.5.100"
    
    # Monitoring Tier
    monitoring:
      hx-dev-monitor-01: "10.1.6.10"
    
    # Management Network
    management:
      bastion: "10.1.10.10"
      ansible_controller: "10.1.10.11"

# =============================================================================
# SHARED NETWORK CONFIGURATION
# =============================================================================
shared_networks:
  # Reserved IP Ranges
  reserved_ranges:
    dhcp_pool_start: ".50"
    dhcp_pool_end: ".99"
    static_range_start: ".10"
    static_range_end: ".49"
    vip_range_start: ".100"
    vip_range_end: ".110"
  
  # Common Network Services
  dns_servers:
    primary: "8.8.8.8"
    secondary: "8.8.4.4"
    tertiary: "1.1.1.1"
  
  ntp_servers:
    primary: "0.pool.ntp.org"
    secondary: "1.pool.ntp.org"
    tertiary: "2.pool.ntp.org"
  
  # VLAN Configuration
  vlans:
    dmz: 10
    private: 20
    management: 30
    storage: 40
    backup: 50

# =============================================================================
# FIREWALL RULES BY IP RANGES
# =============================================================================
firewall_rules:
  # Allow traffic between tiers
  inter_tier_rules:
    - source: "{{ ip_addresses[environment].subnets.web }}"
      destination: "{{ ip_addresses[environment].subnets.application }}"
      ports: [8080, 8081]
      protocol: "tcp"
    
    - source: "{{ ip_addresses[environment].subnets.application }}"
      destination: "{{ ip_addresses[environment].subnets.database }}"
      ports: [5432]
      protocol: "tcp"
    
    - source: "{{ ip_addresses[environment].subnets.application }}"
      destination: "{{ ip_addresses[environment].subnets.cache }}"
      ports: [6379]
      protocol: "tcp"
  
  # Management access rules
  management_rules:
    - source: "{{ ip_addresses[environment].subnets.management }}"
      destination: "any"
      ports: [22]
      protocol: "tcp"
  
  # Monitoring access rules
  monitoring_rules:
    - source: "{{ ip_addresses[environment].subnets.monitoring }}"
      destination: "any"
      ports: [9100, 9187, 9121]
      protocol: "tcp"

# =============================================================================
# LOAD BALANCER VIP CONFIGURATION
# =============================================================================
load_balancer_vips:
  production:
    external_vip: "{{ ip_addresses.production.load_balancer.vip }}"
    internal_vip: "{{ ip_addresses.production.load_balancer.vip }}"
    priority_map:
      hx-prod-lb-01: 100
      hx-prod-lb-02: 90
  
  staging:
    external_vip: "{{ ip_addresses.staging.load_balancer.vip }}"
    internal_vip: "{{ ip_addresses.staging.load_balancer.vip }}"
    priority_map:
      hx-stg-lb-01: 100
      hx-stg-lb-02: 90
  
  development:
    external_vip: "{{ ip_addresses.development.load_balancer.vip }}"
    internal_vip: "{{ ip_addresses.development.load_balancer.vip }}"
    priority_map:
      hx-dev-lb-01: 100
      hx-dev-lb-02: 90

# =============================================================================
# DATABASE CLUSTER VIP CONFIGURATION
# =============================================================================
database_cluster_vips:
  production:
    read_write_vip: "{{ ip_addresses.production.database.cluster_vip }}"
    read_only_vip: "10.0.4.101"
  
  staging:
    read_write_vip: "{{ ip_addresses.staging.database.cluster_vip }}"
    read_only_vip: "10.2.4.101"
  
  development:
    read_write_vip: "{{ ip_addresses.development.database.cluster_vip }}"
    read_only_vip: "10.1.4.101"
