---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == "Debian"

  roles:
    - role: hx_litellm_proxy_standardized
      vars:
        # Override sensitive defaults for testing
        vault_postgres_password: "test_password_123"
        vault_litellm_master_key: "dummy_master_key_32bytes_minimum____"
        vault_litellm_db_password: "test_db_password_123"
        vault_openai_api_key: "sk_test_dummy_key"
        vault_anthropic_api_key: "sk_ant_test_dummy_key"
        # Disable external dependencies for testing
        hx_litellm_providers:
          openai:
            enabled: false
          anthropic:
            enabled: false
        hx_litellm_database_enabled: false
        hx_litellm_caching_enabled: false
