---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: "Verify hx_litellm_proxy_standardized installation"
      block:
        - name: Check if service files exist
          stat:
            path: "{{ item }}"
          register: service_files
          loop:
            - "/etc/systemd/system/hx-litellm-proxy-standardized.service"
          when: "'hx_litellm_proxy_standardized' != 'hx_pg_auth_standardized'"

        - name: Check configuration directories
          stat:
            path: "{{ item }}"
          register: config_dirs
          loop:
            - "/etc/litellm"
            - "/opt/hx-litellm-proxy-standardized"
          failed_when: false

        - name: Verify log directories
          stat:
            path: "{{ item }}"
          register: log_dirs
          loop:
            - "/var/log/litellm"
          failed_when: false

        - name: Display verification results
          debug:
            msg: "Verification completed for hx_litellm_proxy_standardized"
