---
# HX Infrastructure - Development Environment Inventory
# Following Ansible inventory best practices: https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html

# =============================================================================
# LOAD BALANCERS
# =============================================================================
load_balancers:
  hosts:
    hx-dev-lb-01:
      ansible_host: 10.1.1.10
      ansible_user: ubuntu
      server_role: primary
      keepalived_priority: 100
    hx-dev-lb-02:
      ansible_host: 10.1.1.11
      ansible_user: ubuntu
      server_role: backup
      keepalived_priority: 90
  vars:
    environment: development
    tier: load_balancer
    subnet: "{{ network.zones.dmz.subnets.load_balancer }}"

# =============================================================================
# WEB SERVERS
# =============================================================================
web_servers:
  hosts:
    hx-dev-web-01:
      ansible_host: 10.1.2.10
      ansible_user: ubuntu
      server_role: primary
    hx-dev-web-02:
      ansible_host: 10.1.2.11
      ansible_user: ubuntu
      server_role: secondary
  vars:
    environment: development
    tier: web
    subnet: "{{ network.zones.dmz.subnets.web }}"

# =============================================================================
# APPLICATION SERVERS
# =============================================================================
application_servers:
  hosts:
    hx-dev-app-01:
      ansible_host: 10.1.3.10
      ansible_user: ubuntu
      server_role: primary
    hx-dev-app-02:
      ansible_host: 10.1.3.11
      ansible_user: ubuntu
      server_role: secondary
  vars:
    environment: development
    tier: application
    subnet: "{{ network.zones.private.subnets.application }}"

# =============================================================================
# DATABASE SERVERS
# =============================================================================
database_servers:
  hosts:
    hx-dev-db-01:
      ansible_host: 10.1.4.10
      ansible_user: ubuntu
      server_role: master
      postgresql_role: primary
    hx-dev-db-02:
      ansible_host: 10.1.4.11
      ansible_user: ubuntu
      server_role: replica
      postgresql_role: standby
  vars:
    environment: development
    tier: database
    subnet: "{{ network.zones.private.subnets.database }}"

# =============================================================================
# CACHE SERVERS
# =============================================================================
cache_servers:
  hosts:
    hx-dev-cache-01:
      ansible_host: 10.1.5.10
      ansible_user: ubuntu
      server_role: master
      redis_role: primary
  vars:
    environment: development
    tier: cache
    subnet: "{{ network.zones.private.subnets.cache }}"

# =============================================================================
# MONITORING SERVERS
# =============================================================================
monitoring_servers:
  hosts:
    hx-dev-monitor-01:
      ansible_host: 10.1.6.10
      ansible_user: ubuntu
      server_role: primary
      services:
        - prometheus
        - grafana
        - alertmanager
  vars:
    environment: development
    tier: monitoring
    subnet: "{{ network.zones.private.subnets.monitoring }}"

# =============================================================================
# GROUP DEFINITIONS
# =============================================================================
# DMZ Zone (Internet-facing)
dmz:
  children:
    load_balancers:
    web_servers:
  vars:
    zone: dmz
    internet_facing: true
    firewall_rules:
      - port: 80
        protocol: tcp
        source: "0.0.0.0/0"
      - port: 443
        protocol: tcp
        source: "0.0.0.0/0"

# Private Zone (Internal services)
private:
  children:
    application_servers:
    database_servers:
    cache_servers:
    monitoring_servers:
  vars:
    zone: private
    internet_facing: false
    firewall_rules:
      - port: 22
        protocol: tcp
        source: "{{ network.zones.management.subnets.admin }}"

# All Development Servers
development:
  children:
    dmz:
    private:
  vars:
    environment: development
    deployment_type: development
    debug_mode: true
    log_level: debug
    ssl_verification: false
    backup_enabled: false
    monitoring_level: basic
    resource_limits:
      cpu: "2"
      memory: "4G"
      disk: "50G"

# Service-based groupings
postgresql:
  children:
    database_servers:
  vars:
    postgresql_version: "{{ versions.database.postgresql }}"
    postgresql_port: "{{ ports.database.postgresql }}"

redis:
  children:
    cache_servers:
  vars:
    redis_version: "{{ versions.cache.redis }}"
    redis_port: "{{ ports.cache.redis }}"

nginx:
  children:
    load_balancers:
    web_servers:
  vars:
    nginx_version: "{{ versions.web.nginx }}"
    nginx_worker_processes: 2
    nginx_worker_connections: 512

# All servers in development environment
all:
  children:
    development:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=yes -o UserKnownHostsFile=~/.ssh/known_hosts_dev'
    ansible_python_interpreter: /usr/bin/python3
