---
# Security role handlers with hx_ prefix standardization

- name: restart sshd
  systemd:
    name: sshd
    state: restarted
  listen: restart sshd

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
  listen: restart fail2ban

- name: restart auditd
  systemd:
    name: auditd
    state: restarted
  listen: restart auditd

- name: restart ufw
  systemd:
    name: ufw
    state: restarted
  listen: restart ufw

- name: reload ufw
  ufw:
    state: reloaded
  listen: reload ufw
