
---
galaxy_info:
  author: HX Infrastructure Team
  description: Enterprise PostgreSQL authentication and security management
  company: HX AI
  license: MIT
  min_ansible_version: "2.12"
  
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - postgresql
    - database
    - security
    - authentication
    - ssl

dependencies:
  - role: geerlingguy.postgresql
    vars:
      postgresql_version: "14"
      postgresql_data_dir: "/var/lib/postgresql/14/main"
      postgresql_bin_path: "/usr/lib/postgresql/14/bin"
      postgresql_config_path: "/etc/postgresql/14/main"
      postgresql_daemon: postgresql
      postgresql_packages:
        - postgresql
        - postgresql-contrib
        - libpq-dev
        - python3-psycopg2

collections:
  - community.postgresql
  - ansible.posix
