---
# Global variables for all environments
# This centralizes global defaults as recommended in feedback

# HX Infrastructure Global Configuration
hx_project_name: "HX Infrastructure"
hx_organization: "Hanax AI"
hx_admin_email: "admin@hanax.ai"

# Security Configuration
hx_security_hardening: true
hx_fail2ban_enabled: true
hx_firewall_enabled: true
hx_ssh_port: 22
hx_ssh_password_auth: false
hx_ssh_root_login: false

# System Configuration
hx_system_packages:
  - curl
  - wget
  - vim
  - htop
  - git
  - unzip

# Logging Configuration
hx_log_level: INFO
hx_log_retention_days: 30

# Backup Configuration
hx_backup_enabled: true
hx_backup_retention_days: 7

# Monitoring Configuration
hx_monitoring_enabled: true
hx_metrics_collection: true

# Update Configuration
hx_auto_updates: false
hx_security_updates: true
