---
name: Ansible CI/CD Pipeline

on:
  push:
    branches: [ main, develop, 'feature/*' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint
          
      - name: Run YAML Lint
        run: yamllint .
        
      - name: Run Ansible Lint
        run: ansible-lint

  syntax-check:
    name: Syntax Check
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        environment: [dev, test, prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          
      - name: Syntax check for ${{ matrix.environment }}
        run: |
          ansible-playbook --syntax-check \
            -i environments/${{ matrix.environment }}/inventories/hosts.yml \
            site.yml

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run security scan
        run: |
          echo "Security scan placeholder - implement with tools like ansible-vault, bandit, etc."
