---
name: "CodeRabbit AI Review"

'on':
  pull_request: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  coderabbit_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run CodeRabbit AI Review
        uses: coderabbitai/ai-pr-reviewer@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
