# .github/workflows/enhanced-classification-workflow.yml
name: Enhanced AI Classification Workflow
# Phase 2: Advanced Issue Classification Engine
# Processes CodeRabbit findings with AI-powered classification

on:
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode'
        required: false
        default: 'false'
        type: boolean
      classification_only:
        description: 'Only run classification (no remediation)'
        required: false
        default: 'false'
        type: boolean

# P0 FIX: Prevent CI recursion and race conditions
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.HX_COMMIT_TOKEN }}
  PYTHON_VERSION: '3.11'
  CLASSIFICATION_CONFIG: 'scripts/automation/config/classification_config.yml'

# Minimal permissions for security (principle of least privilege)
permissions:
  contents: read

jobs:
  # Job 1: Enhanced Issue Detection and Classification
  enhanced-classification:
    name: AI-Powered Issue Classification
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      pull-requests: write
      statuses: write
    # P0 FIX: Enhanced bot detection to prevent CI recursion
    if: >
      github.event.review.body contains 'coderabbit' || github.event.comment.body contains 'coderabbit' || github.event_name == 'workflow_dispatch'

    outputs:
      issues-detected: ${{ steps.classify.outputs.issues-detected }}
      critical-count: ${{ steps.classify.outputs.critical-count }}
      auto-remediable-count: ${{ steps.classify.outputs.auto-remediable-count }}
      classification-report: ${{ steps.classify.outputs.classification-report }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo 'No requirements.txt found'
        # P0 FIX: Pin Python dependencies for stable CI runs
        pip install scikit-learn==1.3.2 numpy==1.24.4 pandas==2.1.4 pyyaml==6.0.1 requests==2.31.0
        pip install nltk==3.8.1 textblob==0.17.1  # For advanced NLP features

    - name: Configure GitHub CLI
      if: github.event.pull_request.head.repo.fork == false
      shell: bash
      run: |
        gh auth status
        gh auth status
        auth        status
