
name: Nightly Golden Path Tests

on:
  schedule:
    # Run at 2 AM UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  golden-path-tests:
    name: Nightly Golden Path Validation
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Ansible
        run: |
          pip install --upgrade pip
          pip install ansible ansible-lint
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq bc
          
      - name: Run Blue-Green Golden Path Test
        run: |
          echo "=== Blue-Green Golden Path Test ==="
          ./tests/golden_path/blue_green.sh || echo "Blue-Green test failed"
          
      - name: Run Monitoring Golden Path Test  
        run: |
          echo "=== Monitoring Golden Path Test ==="
          ./tests/golden_path/monitoring.sh || echo "Monitoring test failed"
          
      - name: Run Self-Healing Golden Path Test
        run: |
          echo "=== Self-Healing Golden Path Test ==="
          ./tests/golden_path/self_healing.sh || echo "Self-healing test failed"
          
      - name: Run SLO Monitoring
        run: |
          echo "=== SLO Monitoring ==="
          ./scripts/monitoring/slo_monitor.sh staging || echo "SLO monitoring failed"
          
      - name: Run Dashboard Health Check
        run: |
          echo "=== Dashboard Health Check ==="
          ./scripts/monitoring/dashboard_check.sh staging || echo "Dashboard check failed"
          
      - name: Archive test results
        if: always()
        run: |
          mkdir -p nightly_test_results
          cp /tmp/*golden*.log nightly_test_results/ 2>/dev/null || true
          cp /tmp/*slo*.json nightly_test_results/ 2>/dev/null || true
          cp /tmp/*dashboard*.log nightly_test_results/ 2>/dev/null || true
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nightly-golden-test-results-${{ github.run_number }}
          path: nightly_test_results/
          retention-days: 30
          
      - name: Report test status
        if: failure()
        run: |
          echo "⚠️ Nightly golden path tests failed!"
          echo "Check the uploaded artifacts for detailed results."
          echo "This indicates potential drift in the infrastructure."
